from typing import Optional, List, Protocol, Dict, Any

class UserConfiguration:
    username: str
    password: Optional[str]
    two_factor_token: Optional[str]

    def __init__(self, username: str, password:Optional[str] = ..., two_factor_token: Optional[str] = ...) -> None: ...
    @staticmethod
    def adjust_name(username: str) -> str: ...

class ServerConfiguration:
    server: str
    device_id: Optional[bytes]
    server_key_id: Optional[int]

    def __init__(self, server: str, device_id: Optional[bytes] = ..., server_key_id: int = ...) -> None: ...
    @staticmethod
    def adjust_name(server: str) -> str: ...

class Configuration:
    last_username: Optional[str]
    last_server: Optional[str]
    users: List[UserConfiguration]
    servers: List[ServerConfiguration]

    def __init__(self, configuration: Optional[Configuration] = ...): ...
    def get_user_configuration(self, username: str) -> Optional[UserConfiguration]: ...
    def get_server_configuration(self, server: str) -> Optional[ServerConfiguration]: ...

    def merge_user_configuration(self, user_config: UserConfiguration) -> None: ...
    def merge_server_configuration(self, server_config: ServerConfiguration) -> None: ...
    def merge_configuration(self, configuration: Configuration) -> None: ...

class IConfigurationStorage(Protocol):
    def get_configuration(self) -> Configuration:  ...
    def put_configuration(self, configuration: Configuration) -> None: ...

class InMemoryConfigurationStorage(IConfigurationStorage):
    configuration: Configuration

    def __init__(self, configuration: Optional[Configuration] = ...) -> None: ...
    def get_configuration(self) -> Configuration:  ...
    def put_configuration(self, configuration: Configuration) -> None: ...

def json_to_config(json_config: Dict[str, Any]) -> Configuration: ...
def config_to_json(config: Configuration, json_config: Dict[str, Any]) -> None: ...

class JsonConfigurationStorage(IConfigurationStorage):
    file_path: str

    def __init__(self, filename: str) -> None: ...
    def get_configuration(self) -> Configuration:  ...
    def put_configuration(self, configuration: Configuration) -> None: ...
