from typing import Optional, List


class UserConfiguration:
    username: Optional[str] = ...
    password: Optional[str] = ...
    two_factor_token: Optional[str] = ...
    def __init__(self, username: Optional[str] = ..., password:Optional[str] = ..., two_factor_token: Optional[str] = ...) -> None: ...
    @staticmethod
    def adjust_name(username: str) -> str: ...


class ServerConfiguration:
    server: Optional[str] = ...
    device_id: Optional[bytes] = ...
    server_key_id: int = ...
    def __init__(self, server: Optional[str] = ..., device_id: Optional[bytes] = ..., server_key_id: int = ...) -> None: ...
    @staticmethod
    def adjust_name(server: str) -> str: ...


class Configuration:
    users: List[UserConfiguration] = ...
    servers: List[ServerConfiguration] = ...
    last_username: Optional[str] = ...
    last_server: Optional[str] = ...

    def merge_user_configuration(self, user_config: UserConfiguration) -> None: ...
    def merge_server_configuration(self, server_config: ServerConfiguration) -> None: ...
    def merge_configuration(self, configuration: Configuration) -> None: ...
    def get_user_configuration(self, username: str) -> Optional[UserConfiguration]: ...
    def get_server_configuration(self, server: str) -> Optional[ServerConfiguration]: ...


class IConfigurationStorage:
    def get_configuration(self) -> Configuration:  ...
    def put_configuration(self, configuration: Configuration) -> None: ...


class InMemoryConfiguration(IConfigurationStorage):
    def __init__(self, configuration: Optional[Configuration] = ...) -> None: ...


class JsonConfiguration(IConfigurationStorage):
    def __init__(self, filename: str) -> None: ...
