from typing import Optional, BinaryIO, Tuple

from cryptography.hazmat.primitives.asymmetric import ec, rsa

def get_random_bytes(length: int) -> bytes: ...

def generate_rsa_key() -> Tuple[rsa.RSAPrivateKeyWithSerialization, rsa.RSAPublicKeyWithSerialization]: ...
def load_rsa_private_key(der_private_key: bytes, password: Optional[str] = ...) -> rsa.RSAPrivateKeyWithSerialization: ...
def load_rsa_public_key(der_public_key: bytes) -> rsa.RSAPublicKeyWithSerialization: ...
def unload_rsa_private_key(private_key: rsa.RSAPrivateKeyWithSerialization) -> bytes: ...
def unload_rsa_public_key(public_key: rsa.RSAPublicKeyWithSerialization) -> bytes: ...

def generate_ec_key() -> Tuple[ec.EllipticCurvePrivateKeyWithSerialization, ec.EllipticCurvePublicKeyWithSerialization]: ...
def load_ec_private_key(private_key: bytes) -> ec.EllipticCurvePrivateKeyWithSerialization: ...
def load_ec_public_key(public_key: bytes) -> ec.EllipticCurvePublicKeyWithSerialization: ...
def unload_ec_private_key(private_key: ec.EllipticCurvePrivateKeyWithSerialization) -> bytes: ...
def unload_ec_public_key(public_key: ec.EllipticCurvePublicKeyWithSerialization) -> bytes: ...

def encrypt_aes_v1(data: bytes, key: bytes, iv: Optional[bytes] = ..., use_padding: bool = ...) -> bytes: ...
def decrypt_aes_v1(data: bytes, key: bytes, use_padding: bool = ...) -> bytes: ...

def encrypt_aes_v2(data: bytes, key: bytes, nonce: bytes = ...) -> bytes: ...
def decrypt_aes_v2(data: bytes, key: bytes) -> bytes: ...

def encrypt_rsa(data: bytes, rsa_key: rsa.RSAPublicKey) -> bytes: ...
def decrypt_rsa(data: bytes, rsa_key: rsa.RSAPrivateKey) -> bytes: ...

def encrypt_ec(data: bytes, ec_public_key: ec.EllipticCurvePublicKey) -> bytes: ...
def decrypt_ec(data: bytes, ec_private_key: ec.EllipticCurvePrivateKey) -> bytes: ...

def derive_key_v1(password: str, salt: bytes, iterations: int) -> bytes: ...
def derive_keyhash_v1(password: str, salt: bytes, iterations: int) -> bytes: ...
def derive_keyhash_v2(domain: str, password: str, salt: bytes, iterations: int) -> bytes: ...

def hmac_sha512(key: bytes, data: bytes) -> bytes: ...
def create_bio_auth_hash(biometric_key: bytes) -> bytes: ...

class StreamCrypter:
    key: bytes
    is_gcm: bool
    @property
    def bytes_read(self) -> int: ...
    def set_stream(self, stream: BinaryIO, for_encrypt: bool) -> BinaryIO: ...


