from typing import Optional, Any, Protocol

from cryptography.hazmat.primitives.asymmetric.rsa import RSAPublicKey, RSAPrivateKey

def get_random_bytes(length: int) -> bytes: ...

def load_private_key(der_private_key: bytes, password: Optional[str] = ...) -> Any: ...
def load_public_key(der_public_key: bytes) -> Any: ...

def encrypt_aes_v1(data: bytes, key: bytes, iv: Optional[bytes] = ..., use_padding: bool = ...) -> bytes: ...
def decrypt_aes_v1(data: bytes, key: bytes, use_padding: bool = ...) -> bytes: ...

def encrypt_aes_v2(data: bytes, key: bytes, nonce: bytes = ...) -> bytes: ...
def decrypt_aes_v2(data: bytes, key: bytes) -> bytes: ...

def encrypt_rsa(data: bytes, rsa_key: RSAPublicKey) -> bytes: ...
def decrypt_rsa(data: bytes, rsa_key: RSAPrivateKey) -> bytes: ...

def derive_key_v1(password: str, salt: bytes, iterations: int) -> bytes: ...
def derive_keyhash_v1(password: str, salt: bytes, iterations: int) -> bytes: ...
def derive_keyhash_v2(domain: str, password: str, salt: bytes, iterations: int) -> bytes: ...

class StreamCryptor(Protocol):
    def update(self, in_data: bytes) -> bytes: ...
    def finish(self) -> bytes: ...

def aes_v1_stream_decryptor(iv: bytes, key: bytes) -> StreamCryptor: ...
def aes_v1_stream_encryptor(iv: bytes, key: bytes) -> StreamCryptor: ...
