from typing import Optional, TypeVar, Iterable, Generic, Protocol

class IUid(Protocol):
    def uid(self) -> str: ...

U = TypeVar('U', bound=IUid)

class IEntityStorage(Generic[U]):
    def get(self, uid: str) -> Optional[U]:  ...
    def get_all(self) -> Iterable[U]: ...
    def put(self, data: U) -> None:  ...
    def delete(self, uid: str) -> None: ...
    def clear(self) -> None: ...

class IUidLink(Protocol):
    def subject_uid(self) -> str: ...
    def object_uid(self) -> str: ...

L = TypeVar('L', bound=IUidLink)

class IPredicateStorage(Generic[L]):
    def put(self, data: L) -> None: ...
    def delete_link(self, link: IUidLink) -> None: ...
    def get_links_for_subject(self, subject_uid: str) -> Iterable[L]: ...
    def get_links_for_object(self, object_uid: str) -> Iterable[L]: ...
    def get_all_links(self) -> Iterable[L]: ...
    def delete_subject(self, subject_uid: str) -> None: ...
    def delete_object(self, object_uid: str) -> None: ...
    def delete(self, subject_uid: str, object_uid: str) -> None: ...
    def clear(self) -> None: ...

class StorageRecord(IUid):
    record_uid: str = ...
    revision: int = ...
    client_modified_time: int = ...
    data: Optional[str] = ...
    extra: Optional[str] = ...
    udata: Optional[str] = ...
    shared: bool = ...
    owner: bool = ...

class StorageNonSharedData(IUid):
    record_uid: str = ...
    data: str = ...

class StorageSharedFolder(IUid):
    shared_folder_uid: str = ...
    revision: int = ...
    name: str = ...
    default_manage_records: bool = ...
    default_manage_users: bool = ...
    default_can_edit: bool = ...
    default_can_share: bool = ...

class StorageTeam(IUid):
    team_uid: str = ...
    name: str = ...
    team_key: str = ...
    key_type: int = ...
    team_private_key: str = ...
    restrict_edit: bool = ...
    restrict_share: bool = ...
    restrict_view: bool = ...

class StorageRecordKey(IUidLink):
    record_uid: str = ...
    shared_folder_uid: str = ...
    record_key: str = ...
    key_type: int = ...
    can_share: bool = ...
    can_edit: bool = ...

class StorageSharedFolderKey(IUidLink):
    shared_folder_uid: str = ...
    team_uid: str = ...
    key_type: int = ...
    shared_folder_key: str = ...

class StorageSharedFolderPermission(IUidLink):
    shared_folder_uid: str = ...
    user_uid: str = ...
    user_type: int = ...
    manage_records: bool = ...
    manage_users: bool = ...

class StorageFolder(IUid):
    folder_uid: str = ...
    parent_uid: str = ...
    folder_type: str = ...
    folder_key: str = ...
    shared_folder_uid: str = ...
    revision: int = ...
    data: str = ...

class StorageFolderRecordLink(IUidLink):
    folder_uid: str = ...
    record_uid: str = ...

class IKeeperStorage:
    personal_scope_uid: str = ...
    revision: int = ...
    records: IEntityStorage[StorageRecord] = ...
    shared_folders: IEntityStorage[StorageSharedFolder] = ...
    teams: IEntityStorage[StorageTeam] = ...
    non_shared_data: IEntityStorage[StorageNonSharedData] = ...
    record_keys: IPredicateStorage[StorageRecordKey] = ...
    shared_folder_keys: IPredicateStorage[StorageSharedFolderKey] = ...
    shared_folder_permissions: IPredicateStorage[StorageSharedFolderPermission] = ...
    folders: IEntityStorage[StorageFolder] = ...
    folder_records: IPredicateStorage[StorageFolderRecordLink] = ...
    def clear(self) -> None: ...

class InMemoryVaultStorage(IKeeperStorage): ...