import logging
from typing import Iterator


def get_logger(name: str = ...) -> logging.Logger: ...
def generate_uid() -> str: ...
def generate_aes_key() -> bytes: ...
def current_milli_time() -> int: ...
def base64_url_decode(s: str) -> bytes: ...
def base64_url_encode(b: bytes) -> str: ...
def url_strip(url: str) -> str: ...
def decrypt_encryption_params(encryption_params: bytes, password: str) -> bytes: ...
def create_encryption_params(password: str, salt: bytes, iterations: int, data_key: bytes) -> bytes: ...
def create_auth_verifier(password: str, salt: bytes, iterations: int) -> bytes: ...
def is_email(test_str: str) -> bool: ...
def url_strip(url: str) -> str: ...
def password_score(password: str) -> int: ...
def size_to_str(size: int) -> str: ...
def tokenize_searchable_text(text: str) -> Iterator[str]: ...
