from typing import Optional, Iterable, Set, Dict

from .storage import IKeeperStorage
from .vault_types import PasswordRecord, SharedFolder, EnterpriseTeam, Folder

class VaultData:
    storage: IKeeperStorage
    client_key: bytes
    records: Dict[str, PasswordRecord]
    shared_folders: Dict[str, SharedFolder]
    teams: Dict[str, EnterpriseTeam]
    folders: Dict[str, Folder]
    root_folder: Folder

    def __init__(self, client_key: bytes, storage: IKeeperStorage): ...
    def get_record(self, record_uid: str) -> Optional[PasswordRecord]: ...
    def get_all_records(self) -> Iterable[PasswordRecord]: ...
    def get_shared_folder(self, shared_folder_uid: str) -> Optional[SharedFolder]: ...
    def get_all_shared_folders(self) -> Iterable[SharedFolder]: ...
    def get_team(self, team_uid: str) -> Optional[EnterpriseTeam]: ...
    def get_all_teams(self) -> Iterable[EnterpriseTeam]: ...
    def get_folder(self, folder_uid: str) -> Optional[Folder]: ...
    def get_all_folders(self) -> Iterable[EnterpriseTeam]: ...
    def rebuild_data(self, changes: RebuildTask) -> None: ...
    def build_folders(self) -> None: ...


class RebuildTask:
    is_full_sync: bool
    records: Set[str]
    shared_folders: Set[str]

    def __init__(self, full_sync: bool) -> None: ...
    def add_record(self, record_uid: str) -> None: ...
    def add_shared_folder(self, shared_folder_uid: str) -> None: ...


