from typing import Optional, Iterable, Protocol

from .storage import IKeeperStorage
from .vault_types import PasswordRecord, SharedFolder, EnterpriseTeam, Folder

class IRebuildTask(Protocol):
    is_full_sync: bool

    def add_record(self, record_uid: str) -> None: ...
    def add_shared_folder(self, shared_folder_uid: str) -> None: ...

class IVaultData(Protocol):
    storage: IKeeperStorage
    client_key: bytes
    root_folder: Folder
    record_count: int
    shared_folder_count: int
    team_count: int

    def get_record(self, record_uid: str) -> Optional[PasswordRecord]: ...
    def get_all_records(self) -> Iterable[PasswordRecord]: ...
    def get_shared_folder(self, shared_folder_uid: str) -> Optional[SharedFolder]: ...
    def get_all_shared_folders(self) -> Iterable[SharedFolder]: ...
    def get_team(self, team_uid: str) -> Optional[EnterpriseTeam]: ...
    def get_all_teams(self) -> Iterable[EnterpriseTeam]: ...
    def get_folder(self, folder_uid: str) -> Optional[Folder]: ...
    def get_all_folders(self) -> Iterable[EnterpriseTeam]: ...
    def rebuild_data(self, changes: IRebuildTask) -> None: ...
    def build_folders(self) -> None: ...

class VaultData(IVaultData):
    def __init__(self, client_key: bytes, storage: IKeeperStorage): ...

class RebuildTask(IRebuildTask):
    def __init__(self, full_sync: bool) -> None: ...

