"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.struct_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Currency:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CurrencyEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Currency.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN: _Currency.ValueType  # 0
    USD: _Currency.ValueType  # 1
    GBP: _Currency.ValueType  # 2
    JPY: _Currency.ValueType  # 3
    EUR: _Currency.ValueType  # 4
    AUD: _Currency.ValueType  # 5
    CAD: _Currency.ValueType  # 6

class Currency(_Currency, metaclass=_CurrencyEnumTypeWrapper): ...

UNKNOWN: Currency.ValueType  # 0
USD: Currency.ValueType  # 1
GBP: Currency.ValueType  # 2
JPY: Currency.ValueType  # 3
EUR: Currency.ValueType  # 4
AUD: Currency.ValueType  # 5
CAD: Currency.ValueType  # 6
global___Currency = Currency

class _GradientIntegrationStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GradientIntegrationStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GradientIntegrationStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NOTCONNECTED: _GradientIntegrationStatus.ValueType  # 0
    PENDING: _GradientIntegrationStatus.ValueType  # 1
    CONNECTED: _GradientIntegrationStatus.ValueType  # 2
    NONE: _GradientIntegrationStatus.ValueType  # 3

class GradientIntegrationStatus(_GradientIntegrationStatus, metaclass=_GradientIntegrationStatusEnumTypeWrapper): ...

NOTCONNECTED: GradientIntegrationStatus.ValueType  # 0
PENDING: GradientIntegrationStatus.ValueType  # 1
CONNECTED: GradientIntegrationStatus.ValueType  # 2
NONE: GradientIntegrationStatus.ValueType  # 3
global___GradientIntegrationStatus = GradientIntegrationStatus

class _EventType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EventTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EventType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN_TRACKING_EVENT_TYPE: _EventType.ValueType  # 0
    TRACKING_POPUP_DISPLAYED: _EventType.ValueType  # 1
    TRACKING_POPUP_ACCEPTED: _EventType.ValueType  # 2
    TRACKING_POPUP_DISMISSED: _EventType.ValueType  # 3
    TRACKING_POPUP_PAID: _EventType.ValueType  # 4
    TRACKING_PUSH_CLICKED: _EventType.ValueType  # 5
    CONSOLE_ACTION: _EventType.ValueType  # 6
    VAULT_ACTION: _EventType.ValueType  # 7

class EventType(_EventType, metaclass=_EventTypeEnumTypeWrapper): ...

UNKNOWN_TRACKING_EVENT_TYPE: EventType.ValueType  # 0
TRACKING_POPUP_DISPLAYED: EventType.ValueType  # 1
TRACKING_POPUP_ACCEPTED: EventType.ValueType  # 2
TRACKING_POPUP_DISMISSED: EventType.ValueType  # 3
TRACKING_POPUP_PAID: EventType.ValueType  # 4
TRACKING_PUSH_CLICKED: EventType.ValueType  # 5
CONSOLE_ACTION: EventType.ValueType  # 6
VAULT_ACTION: EventType.ValueType  # 7
global___EventType = EventType

class _PurchaseProductType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PurchaseProductTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PurchaseProductType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    upgradeToEnterprise: _PurchaseProductType.ValueType  # 0
    addUsers: _PurchaseProductType.ValueType  # 1
    addStorage: _PurchaseProductType.ValueType  # 2
    addAudit: _PurchaseProductType.ValueType  # 3
    addBreachWatch: _PurchaseProductType.ValueType  # 4
    addCompliance: _PurchaseProductType.ValueType  # 5
    addChat: _PurchaseProductType.ValueType  # 6
    addPAM: _PurchaseProductType.ValueType  # 7
    addSilverSupport: _PurchaseProductType.ValueType  # 8
    addPlatinumSupport: _PurchaseProductType.ValueType  # 9

class PurchaseProductType(_PurchaseProductType, metaclass=_PurchaseProductTypeEnumTypeWrapper): ...

upgradeToEnterprise: PurchaseProductType.ValueType  # 0
addUsers: PurchaseProductType.ValueType  # 1
addStorage: PurchaseProductType.ValueType  # 2
addAudit: PurchaseProductType.ValueType  # 3
addBreachWatch: PurchaseProductType.ValueType  # 4
addCompliance: PurchaseProductType.ValueType  # 5
addChat: PurchaseProductType.ValueType  # 6
addPAM: PurchaseProductType.ValueType  # 7
addSilverSupport: PurchaseProductType.ValueType  # 8
addPlatinumSupport: PurchaseProductType.ValueType  # 9
global___PurchaseProductType = PurchaseProductType

@typing.final
class ValidateSessionTokenRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENCRYPTEDSESSIONTOKEN_FIELD_NUMBER: builtins.int
    RETURNMCENTERPISEIDS_FIELD_NUMBER: builtins.int
    IP_FIELD_NUMBER: builtins.int
    encryptedSessionToken: builtins.bytes
    returnMcEnterpiseIds: builtins.bool
    ip: builtins.str
    def __init__(
        self,
        *,
        encryptedSessionToken: builtins.bytes = ...,
        returnMcEnterpiseIds: builtins.bool = ...,
        ip: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["encryptedSessionToken", b"encryptedSessionToken", "ip", b"ip", "returnMcEnterpiseIds", b"returnMcEnterpiseIds"]) -> None: ...

global___ValidateSessionTokenRequest = ValidateSessionTokenRequest

@typing.final
class ValidateSessionTokenResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Status:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ValidateSessionTokenResponse._Status.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        VALID: ValidateSessionTokenResponse._Status.ValueType  # 0
        NOT_VALID: ValidateSessionTokenResponse._Status.ValueType  # 1
        EXPIRED: ValidateSessionTokenResponse._Status.ValueType  # 2
        IP_BLOCKED: ValidateSessionTokenResponse._Status.ValueType  # 3
        INVALID_CLIENT_VERSION: ValidateSessionTokenResponse._Status.ValueType  # 4

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    VALID: ValidateSessionTokenResponse.Status.ValueType  # 0
    NOT_VALID: ValidateSessionTokenResponse.Status.ValueType  # 1
    EXPIRED: ValidateSessionTokenResponse.Status.ValueType  # 2
    IP_BLOCKED: ValidateSessionTokenResponse.Status.ValueType  # 3
    INVALID_CLIENT_VERSION: ValidateSessionTokenResponse.Status.ValueType  # 4

    USERNAME_FIELD_NUMBER: builtins.int
    USERID_FIELD_NUMBER: builtins.int
    ENTERPRISEUSERID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    STATUSMESSAGE_FIELD_NUMBER: builtins.int
    MCENTERPRISEIDS_FIELD_NUMBER: builtins.int
    HASMSPPERMISSION_FIELD_NUMBER: builtins.int
    DELETEDMCENTERPRISEIDS_FIELD_NUMBER: builtins.int
    username: builtins.str
    userId: builtins.int
    enterpriseUserId: builtins.int
    status: global___ValidateSessionTokenResponse.Status.ValueType
    statusMessage: builtins.str
    hasMSPPermission: builtins.bool
    @property
    def mcEnterpriseIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def deletedMcEnterpriseIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        userId: builtins.int = ...,
        enterpriseUserId: builtins.int = ...,
        status: global___ValidateSessionTokenResponse.Status.ValueType = ...,
        statusMessage: builtins.str = ...,
        mcEnterpriseIds: collections.abc.Iterable[builtins.int] | None = ...,
        hasMSPPermission: builtins.bool = ...,
        deletedMcEnterpriseIds: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["deletedMcEnterpriseIds", b"deletedMcEnterpriseIds", "enterpriseUserId", b"enterpriseUserId", "hasMSPPermission", b"hasMSPPermission", "mcEnterpriseIds", b"mcEnterpriseIds", "status", b"status", "statusMessage", b"statusMessage", "userId", b"userId", "username", b"username"]) -> None: ...

global___ValidateSessionTokenResponse = ValidateSessionTokenResponse

@typing.final
class SubscriptionStatusRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/v2/console/subscription/status"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___SubscriptionStatusRequest = SubscriptionStatusRequest

@typing.final
class SubscriptionStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTORENEWAL_FIELD_NUMBER: builtins.int
    CURRENTPAYMENTMETHOD_FIELD_NUMBER: builtins.int
    CHECKOUTLINK_FIELD_NUMBER: builtins.int
    LICENSECREATEDATE_FIELD_NUMBER: builtins.int
    ISDISTRIBUTOR_FIELD_NUMBER: builtins.int
    ISLEGACYMSP_FIELD_NUMBER: builtins.int
    LICENSESTATS_FIELD_NUMBER: builtins.int
    GRADIENTSTATUS_FIELD_NUMBER: builtins.int
    HIDETRIALBANNER_FIELD_NUMBER: builtins.int
    GRADIENTLASTSYNCDATE_FIELD_NUMBER: builtins.int
    GRADIENTNEXTSYNCDATE_FIELD_NUMBER: builtins.int
    ISGRADIENTMAPPINGPENDING_FIELD_NUMBER: builtins.int
    checkoutLink: builtins.str
    licenseCreateDate: builtins.int
    isDistributor: builtins.bool
    isLegacyMsp: builtins.bool
    gradientStatus: global___GradientIntegrationStatus.ValueType
    hideTrialBanner: builtins.bool
    gradientLastSyncDate: builtins.str
    gradientNextSyncDate: builtins.str
    isGradientMappingPending: builtins.bool
    @property
    def autoRenewal(self) -> global___AutoRenewal: ...
    @property
    def currentPaymentMethod(self) -> global___PaymentMethod: ...
    @property
    def licenseStats(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LicenseStats]: ...
    def __init__(
        self,
        *,
        autoRenewal: global___AutoRenewal | None = ...,
        currentPaymentMethod: global___PaymentMethod | None = ...,
        checkoutLink: builtins.str = ...,
        licenseCreateDate: builtins.int = ...,
        isDistributor: builtins.bool = ...,
        isLegacyMsp: builtins.bool = ...,
        licenseStats: collections.abc.Iterable[global___LicenseStats] | None = ...,
        gradientStatus: global___GradientIntegrationStatus.ValueType = ...,
        hideTrialBanner: builtins.bool = ...,
        gradientLastSyncDate: builtins.str = ...,
        gradientNextSyncDate: builtins.str = ...,
        isGradientMappingPending: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["autoRenewal", b"autoRenewal", "currentPaymentMethod", b"currentPaymentMethod"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["autoRenewal", b"autoRenewal", "checkoutLink", b"checkoutLink", "currentPaymentMethod", b"currentPaymentMethod", "gradientLastSyncDate", b"gradientLastSyncDate", "gradientNextSyncDate", b"gradientNextSyncDate", "gradientStatus", b"gradientStatus", "hideTrialBanner", b"hideTrialBanner", "isDistributor", b"isDistributor", "isGradientMappingPending", b"isGradientMappingPending", "isLegacyMsp", b"isLegacyMsp", "licenseCreateDate", b"licenseCreateDate", "licenseStats", b"licenseStats"]) -> None: ...

global___SubscriptionStatusResponse = SubscriptionStatusResponse

@typing.final
class LicenseStats(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[LicenseStats._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        LICENSE_STAT_UNKNOWN: LicenseStats._Type.ValueType  # 0
        MSP_BASE: LicenseStats._Type.ValueType  # 1
        MC_BUSINESS: LicenseStats._Type.ValueType  # 2
        MC_BUSINESS_PLUS: LicenseStats._Type.ValueType  # 3
        MC_ENTERPRISE: LicenseStats._Type.ValueType  # 4
        MC_ENTERPRISE_PLUS: LicenseStats._Type.ValueType  # 5
        B2B_BUSINESS_STARTER: LicenseStats._Type.ValueType  # 6
        B2B_BUSINESS: LicenseStats._Type.ValueType  # 7
        B2B_ENTERPRISE: LicenseStats._Type.ValueType  # 8

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    LICENSE_STAT_UNKNOWN: LicenseStats.Type.ValueType  # 0
    MSP_BASE: LicenseStats.Type.ValueType  # 1
    MC_BUSINESS: LicenseStats.Type.ValueType  # 2
    MC_BUSINESS_PLUS: LicenseStats.Type.ValueType  # 3
    MC_ENTERPRISE: LicenseStats.Type.ValueType  # 4
    MC_ENTERPRISE_PLUS: LicenseStats.Type.ValueType  # 5
    B2B_BUSINESS_STARTER: LicenseStats.Type.ValueType  # 6
    B2B_BUSINESS: LicenseStats.Type.ValueType  # 7
    B2B_ENTERPRISE: LicenseStats.Type.ValueType  # 8

    TYPE_FIELD_NUMBER: builtins.int
    AVAILABLE_FIELD_NUMBER: builtins.int
    USED_FIELD_NUMBER: builtins.int
    type: global___LicenseStats.Type.ValueType
    available: builtins.int
    used: builtins.int
    def __init__(
        self,
        *,
        type: global___LicenseStats.Type.ValueType = ...,
        available: builtins.int = ...,
        used: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["available", b"available", "type", b"type", "used", b"used"]) -> None: ...

global___LicenseStats = LicenseStats

@typing.final
class AutoRenewal(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NEXTON_FIELD_NUMBER: builtins.int
    DAYSLEFT_FIELD_NUMBER: builtins.int
    ISTRIAL_FIELD_NUMBER: builtins.int
    nextOn: builtins.int
    daysLeft: builtins.int
    isTrial: builtins.bool
    def __init__(
        self,
        *,
        nextOn: builtins.int = ...,
        daysLeft: builtins.int = ...,
        isTrial: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["daysLeft", b"daysLeft", "isTrial", b"isTrial", "nextOn", b"nextOn"]) -> None: ...

global___AutoRenewal = AutoRenewal

@typing.final
class PaymentMethod(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[PaymentMethod._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        CARD: PaymentMethod._Type.ValueType  # 0
        SEPA: PaymentMethod._Type.ValueType  # 1
        PAYPAL: PaymentMethod._Type.ValueType  # 2
        NONE: PaymentMethod._Type.ValueType  # 3
        VENDOR: PaymentMethod._Type.ValueType  # 4
        PURCHASEORDER: PaymentMethod._Type.ValueType  # 5

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    CARD: PaymentMethod.Type.ValueType  # 0
    SEPA: PaymentMethod.Type.ValueType  # 1
    PAYPAL: PaymentMethod.Type.ValueType  # 2
    NONE: PaymentMethod.Type.ValueType  # 3
    VENDOR: PaymentMethod.Type.ValueType  # 4
    PURCHASEORDER: PaymentMethod.Type.ValueType  # 5

    @typing.final
    class Card(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        LAST4_FIELD_NUMBER: builtins.int
        BRAND_FIELD_NUMBER: builtins.int
        last4: builtins.str
        brand: builtins.str
        def __init__(
            self,
            *,
            last4: builtins.str = ...,
            brand: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["brand", b"brand", "last4", b"last4"]) -> None: ...

    @typing.final
    class Sepa(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        LAST4_FIELD_NUMBER: builtins.int
        COUNTRY_FIELD_NUMBER: builtins.int
        last4: builtins.str
        country: builtins.str
        def __init__(
            self,
            *,
            last4: builtins.str = ...,
            country: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["country", b"country", "last4", b"last4"]) -> None: ...

    @typing.final
    class Paypal(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @typing.final
    class Vendor(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        name: builtins.str
        def __init__(
            self,
            *,
            name: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

    @typing.final
    class PurchaseOrder(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        name: builtins.str
        def __init__(
            self,
            *,
            name: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

    TYPE_FIELD_NUMBER: builtins.int
    CARD_FIELD_NUMBER: builtins.int
    SEPA_FIELD_NUMBER: builtins.int
    PAYPAL_FIELD_NUMBER: builtins.int
    FAILEDBILLING_FIELD_NUMBER: builtins.int
    VENDOR_FIELD_NUMBER: builtins.int
    PURCHASEORDER_FIELD_NUMBER: builtins.int
    type: global___PaymentMethod.Type.ValueType
    failedBilling: builtins.bool
    @property
    def card(self) -> global___PaymentMethod.Card: ...
    @property
    def sepa(self) -> global___PaymentMethod.Sepa: ...
    @property
    def paypal(self) -> global___PaymentMethod.Paypal: ...
    @property
    def vendor(self) -> global___PaymentMethod.Vendor: ...
    @property
    def purchaseOrder(self) -> global___PaymentMethod.PurchaseOrder: ...
    def __init__(
        self,
        *,
        type: global___PaymentMethod.Type.ValueType = ...,
        card: global___PaymentMethod.Card | None = ...,
        sepa: global___PaymentMethod.Sepa | None = ...,
        paypal: global___PaymentMethod.Paypal | None = ...,
        failedBilling: builtins.bool = ...,
        vendor: global___PaymentMethod.Vendor | None = ...,
        purchaseOrder: global___PaymentMethod.PurchaseOrder | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["card", b"card", "paypal", b"paypal", "purchaseOrder", b"purchaseOrder", "sepa", b"sepa", "vendor", b"vendor"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["card", b"card", "failedBilling", b"failedBilling", "paypal", b"paypal", "purchaseOrder", b"purchaseOrder", "sepa", b"sepa", "type", b"type", "vendor", b"vendor"]) -> None: ...

global___PaymentMethod = PaymentMethod

@typing.final
class SubscriptionMspPricingRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/v2/console/subscription/mc_pricing"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___SubscriptionMspPricingRequest = SubscriptionMspPricingRequest

@typing.final
class SubscriptionMspPricingResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDONS_FIELD_NUMBER: builtins.int
    FILEPLANS_FIELD_NUMBER: builtins.int
    @property
    def addons(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Addon]: ...
    @property
    def filePlans(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FilePlan]: ...
    def __init__(
        self,
        *,
        addons: collections.abc.Iterable[global___Addon] | None = ...,
        filePlans: collections.abc.Iterable[global___FilePlan] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["addons", b"addons", "filePlans", b"filePlans"]) -> None: ...

global___SubscriptionMspPricingResponse = SubscriptionMspPricingResponse

@typing.final
class SubscriptionMcPricingRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/v2/console/subscription/mc_pricing"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___SubscriptionMcPricingRequest = SubscriptionMcPricingRequest

@typing.final
class SubscriptionMcPricingResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BASEPLANS_FIELD_NUMBER: builtins.int
    ADDONS_FIELD_NUMBER: builtins.int
    FILEPLANS_FIELD_NUMBER: builtins.int
    @property
    def basePlans(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BasePlan]: ...
    @property
    def addons(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Addon]: ...
    @property
    def filePlans(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FilePlan]: ...
    def __init__(
        self,
        *,
        basePlans: collections.abc.Iterable[global___BasePlan] | None = ...,
        addons: collections.abc.Iterable[global___Addon] | None = ...,
        filePlans: collections.abc.Iterable[global___FilePlan] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["addons", b"addons", "basePlans", b"basePlans", "filePlans", b"filePlans"]) -> None: ...

global___SubscriptionMcPricingResponse = SubscriptionMcPricingResponse

@typing.final
class BasePlan(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    COST_FIELD_NUMBER: builtins.int
    id: builtins.int
    @property
    def cost(self) -> global___Cost: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        cost: global___Cost | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["cost", b"cost"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["cost", b"cost", "id", b"id"]) -> None: ...

global___BasePlan = BasePlan

@typing.final
class Addon(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    COST_FIELD_NUMBER: builtins.int
    AMOUNTCONSUMED_FIELD_NUMBER: builtins.int
    id: builtins.int
    amountConsumed: builtins.int
    @property
    def cost(self) -> global___Cost: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        cost: global___Cost | None = ...,
        amountConsumed: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["cost", b"cost"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["amountConsumed", b"amountConsumed", "cost", b"cost", "id", b"id"]) -> None: ...

global___Addon = Addon

@typing.final
class FilePlan(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    COST_FIELD_NUMBER: builtins.int
    id: builtins.int
    @property
    def cost(self) -> global___Cost: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        cost: global___Cost | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["cost", b"cost"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["cost", b"cost", "id", b"id"]) -> None: ...

global___FilePlan = FilePlan

@typing.final
class Cost(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _AmountPer:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _AmountPerEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Cost._AmountPer.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: Cost._AmountPer.ValueType  # 0
        MONTH: Cost._AmountPer.ValueType  # 1
        USER_MONTH: Cost._AmountPer.ValueType  # 2
        USER_CONSUMED_MONTH: Cost._AmountPer.ValueType  # 3
        ENDPOINT_MONTH: Cost._AmountPer.ValueType  # 4
        USER_YEAR: Cost._AmountPer.ValueType  # 5
        USER_CONSUMED_YEAR: Cost._AmountPer.ValueType  # 6
        YEAR: Cost._AmountPer.ValueType  # 7
        ENDPOINT_YEAR: Cost._AmountPer.ValueType  # 8

    class AmountPer(_AmountPer, metaclass=_AmountPerEnumTypeWrapper): ...
    UNKNOWN: Cost.AmountPer.ValueType  # 0
    MONTH: Cost.AmountPer.ValueType  # 1
    USER_MONTH: Cost.AmountPer.ValueType  # 2
    USER_CONSUMED_MONTH: Cost.AmountPer.ValueType  # 3
    ENDPOINT_MONTH: Cost.AmountPer.ValueType  # 4
    USER_YEAR: Cost.AmountPer.ValueType  # 5
    USER_CONSUMED_YEAR: Cost.AmountPer.ValueType  # 6
    YEAR: Cost.AmountPer.ValueType  # 7
    ENDPOINT_YEAR: Cost.AmountPer.ValueType  # 8

    AMOUNT_FIELD_NUMBER: builtins.int
    AMOUNTPER_FIELD_NUMBER: builtins.int
    CURRENCY_FIELD_NUMBER: builtins.int
    amount: builtins.float
    amountPer: global___Cost.AmountPer.ValueType
    currency: global___Currency.ValueType
    def __init__(
        self,
        *,
        amount: builtins.float = ...,
        amountPer: global___Cost.AmountPer.ValueType = ...,
        currency: global___Currency.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["amount", b"amount", "amountPer", b"amountPer", "currency", b"currency"]) -> None: ...

global___Cost = Cost

@typing.final
class InvoiceSearchRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/v2/console/invoice/search"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SIZE_FIELD_NUMBER: builtins.int
    STARTINGAFTERID_FIELD_NUMBER: builtins.int
    ALLINVOICESUNFILTERED_FIELD_NUMBER: builtins.int
    size: builtins.int
    startingAfterId: builtins.int
    allInvoicesUnfiltered: builtins.bool
    """When set to true, returns both enterprise and msp invoices.  Does not return price masked invoices or invoices missing required data."""
    def __init__(
        self,
        *,
        size: builtins.int = ...,
        startingAfterId: builtins.int = ...,
        allInvoicesUnfiltered: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["allInvoicesUnfiltered", b"allInvoicesUnfiltered", "size", b"size", "startingAfterId", b"startingAfterId"]) -> None: ...

global___InvoiceSearchRequest = InvoiceSearchRequest

@typing.final
class InvoiceSearchResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INVOICES_FIELD_NUMBER: builtins.int
    @property
    def invoices(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Invoice]: ...
    def __init__(
        self,
        *,
        invoices: collections.abc.Iterable[global___Invoice] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["invoices", b"invoices"]) -> None: ...

global___InvoiceSearchResponse = InvoiceSearchResponse

@typing.final
class Invoice(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Invoice._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: Invoice._Type.ValueType  # 0
        NEW: Invoice._Type.ValueType  # 1
        RENEWAL: Invoice._Type.ValueType  # 2
        UPGRADE: Invoice._Type.ValueType  # 3
        RESTORE: Invoice._Type.ValueType  # 4
        ASSOCIATION: Invoice._Type.ValueType  # 5
        OVERAGE: Invoice._Type.ValueType  # 6

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    UNKNOWN: Invoice.Type.ValueType  # 0
    NEW: Invoice.Type.ValueType  # 1
    RENEWAL: Invoice.Type.ValueType  # 2
    UPGRADE: Invoice.Type.ValueType  # 3
    RESTORE: Invoice.Type.ValueType  # 4
    ASSOCIATION: Invoice.Type.ValueType  # 5
    OVERAGE: Invoice.Type.ValueType  # 6

    @typing.final
    class Cost(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        AMOUNT_FIELD_NUMBER: builtins.int
        CURRENCY_FIELD_NUMBER: builtins.int
        amount: builtins.float
        currency: global___Currency.ValueType
        def __init__(
            self,
            *,
            amount: builtins.float = ...,
            currency: global___Currency.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["amount", b"amount", "currency", b"currency"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    INVOICENUMBER_FIELD_NUMBER: builtins.int
    INVOICEDATE_FIELD_NUMBER: builtins.int
    LICENSECOUNT_FIELD_NUMBER: builtins.int
    TOTALCOST_FIELD_NUMBER: builtins.int
    INVOICETYPE_FIELD_NUMBER: builtins.int
    id: builtins.int
    invoiceNumber: builtins.str
    invoiceDate: builtins.int
    licenseCount: builtins.int
    invoiceType: global___Invoice.Type.ValueType
    @property
    def totalCost(self) -> global___Invoice.Cost: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        invoiceNumber: builtins.str = ...,
        invoiceDate: builtins.int = ...,
        licenseCount: builtins.int = ...,
        totalCost: global___Invoice.Cost | None = ...,
        invoiceType: global___Invoice.Type.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["totalCost", b"totalCost"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "invoiceDate", b"invoiceDate", "invoiceNumber", b"invoiceNumber", "invoiceType", b"invoiceType", "licenseCount", b"licenseCount", "totalCost", b"totalCost"]) -> None: ...

global___Invoice = Invoice

@typing.final
class VaultInvoicesListRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/rest/vault/invoices/list"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___VaultInvoicesListRequest = VaultInvoicesListRequest

@typing.final
class VaultInvoicesListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INVOICES_FIELD_NUMBER: builtins.int
    @property
    def invoices(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___VaultInvoice]: ...
    def __init__(
        self,
        *,
        invoices: collections.abc.Iterable[global___VaultInvoice] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["invoices", b"invoices"]) -> None: ...

global___VaultInvoicesListResponse = VaultInvoicesListResponse

@typing.final
class VaultInvoice(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    INVOICENUMBER_FIELD_NUMBER: builtins.int
    DATECREATED_FIELD_NUMBER: builtins.int
    TOTAL_FIELD_NUMBER: builtins.int
    PURCHASETYPE_FIELD_NUMBER: builtins.int
    id: builtins.int
    invoiceNumber: builtins.str
    dateCreated: builtins.int
    purchaseType: global___Invoice.Type.ValueType
    @property
    def total(self) -> global___Invoice.Cost: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        invoiceNumber: builtins.str = ...,
        dateCreated: builtins.int = ...,
        total: global___Invoice.Cost | None = ...,
        purchaseType: global___Invoice.Type.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["total", b"total"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["dateCreated", b"dateCreated", "id", b"id", "invoiceNumber", b"invoiceNumber", "purchaseType", b"purchaseType", "total", b"total"]) -> None: ...

global___VaultInvoice = VaultInvoice

@typing.final
class InvoiceDownloadRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/v2/enterprise_console/invoice/download"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INVOICENUMBER_FIELD_NUMBER: builtins.int
    invoiceNumber: builtins.str
    def __init__(
        self,
        *,
        invoiceNumber: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["invoiceNumber", b"invoiceNumber"]) -> None: ...

global___InvoiceDownloadRequest = InvoiceDownloadRequest

@typing.final
class InvoiceDownloadResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LINK_FIELD_NUMBER: builtins.int
    FILENAME_FIELD_NUMBER: builtins.int
    link: builtins.str
    fileName: builtins.str
    def __init__(
        self,
        *,
        link: builtins.str = ...,
        fileName: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["fileName", b"fileName", "link", b"link"]) -> None: ...

global___InvoiceDownloadResponse = InvoiceDownloadResponse

@typing.final
class VaultInvoiceDownloadLinkRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/rest/vault/invoice/download_link"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INVOICENUMBER_FIELD_NUMBER: builtins.int
    invoiceNumber: builtins.str
    def __init__(
        self,
        *,
        invoiceNumber: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["invoiceNumber", b"invoiceNumber"]) -> None: ...

global___VaultInvoiceDownloadLinkRequest = VaultInvoiceDownloadLinkRequest

@typing.final
class VaultInvoiceDownloadLinkResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LINK_FIELD_NUMBER: builtins.int
    FILENAME_FIELD_NUMBER: builtins.int
    link: builtins.str
    fileName: builtins.str
    def __init__(
        self,
        *,
        link: builtins.str = ...,
        fileName: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["fileName", b"fileName", "link", b"link"]) -> None: ...

global___VaultInvoiceDownloadLinkResponse = VaultInvoiceDownloadLinkResponse

@typing.final
class ReportingDailySnapshotRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/v2/console/reporting/daily_snapshot"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MONTH_FIELD_NUMBER: builtins.int
    YEAR_FIELD_NUMBER: builtins.int
    month: builtins.int
    year: builtins.int
    def __init__(
        self,
        *,
        month: builtins.int = ...,
        year: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["month", b"month", "year", b"year"]) -> None: ...

global___ReportingDailySnapshotRequest = ReportingDailySnapshotRequest

@typing.final
class ReportingDailySnapshotResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORDS_FIELD_NUMBER: builtins.int
    MCENTERPRISES_FIELD_NUMBER: builtins.int
    @property
    def records(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SnapshotRecord]: ...
    @property
    def mcEnterprises(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SnapshotMcEnterprise]: ...
    def __init__(
        self,
        *,
        records: collections.abc.Iterable[global___SnapshotRecord] | None = ...,
        mcEnterprises: collections.abc.Iterable[global___SnapshotMcEnterprise] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["mcEnterprises", b"mcEnterprises", "records", b"records"]) -> None: ...

global___ReportingDailySnapshotResponse = ReportingDailySnapshotResponse

@typing.final
class SnapshotRecord(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Addon(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        MAXADDONID_FIELD_NUMBER: builtins.int
        UNITS_FIELD_NUMBER: builtins.int
        maxAddonId: builtins.int
        units: builtins.int
        def __init__(
            self,
            *,
            maxAddonId: builtins.int = ...,
            units: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["maxAddonId", b"maxAddonId", "units", b"units"]) -> None: ...

    DATE_FIELD_NUMBER: builtins.int
    MCENTERPRISEID_FIELD_NUMBER: builtins.int
    MAXLICENSECOUNT_FIELD_NUMBER: builtins.int
    MAXFILEPLANTYPEID_FIELD_NUMBER: builtins.int
    MAXBASEPLANID_FIELD_NUMBER: builtins.int
    ADDONS_FIELD_NUMBER: builtins.int
    date: builtins.int
    mcEnterpriseId: builtins.int
    maxLicenseCount: builtins.int
    maxFilePlanTypeId: builtins.int
    maxBasePlanId: builtins.int
    @property
    def addons(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SnapshotRecord.Addon]: ...
    def __init__(
        self,
        *,
        date: builtins.int = ...,
        mcEnterpriseId: builtins.int = ...,
        maxLicenseCount: builtins.int = ...,
        maxFilePlanTypeId: builtins.int = ...,
        maxBasePlanId: builtins.int = ...,
        addons: collections.abc.Iterable[global___SnapshotRecord.Addon] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["addons", b"addons", "date", b"date", "maxBasePlanId", b"maxBasePlanId", "maxFilePlanTypeId", b"maxFilePlanTypeId", "maxLicenseCount", b"maxLicenseCount", "mcEnterpriseId", b"mcEnterpriseId"]) -> None: ...

global___SnapshotRecord = SnapshotRecord

@typing.final
class SnapshotMcEnterprise(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    id: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "name", b"name"]) -> None: ...

global___SnapshotMcEnterprise = SnapshotMcEnterprise

@typing.final
class MappingAddonsRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/v2/enterprise_console/mapping/addons"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MappingAddonsRequest = MappingAddonsRequest

@typing.final
class MappingAddonsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDONS_FIELD_NUMBER: builtins.int
    FILEPLANS_FIELD_NUMBER: builtins.int
    @property
    def addons(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MappingItem]: ...
    @property
    def filePlans(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MappingItem]: ...
    def __init__(
        self,
        *,
        addons: collections.abc.Iterable[global___MappingItem] | None = ...,
        filePlans: collections.abc.Iterable[global___MappingItem] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["addons", b"addons", "filePlans", b"filePlans"]) -> None: ...

global___MappingAddonsResponse = MappingAddonsResponse

@typing.final
class MappingItem(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    id: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "name", b"name"]) -> None: ...

global___MappingItem = MappingItem

@typing.final
class GradientValidateKeyRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/v2/enterprise_console/gradient/validate-key"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GRADIENTKEY_FIELD_NUMBER: builtins.int
    gradientKey: builtins.str
    def __init__(
        self,
        *,
        gradientKey: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["gradientKey", b"gradientKey"]) -> None: ...

global___GradientValidateKeyRequest = GradientValidateKeyRequest

@typing.final
class GradientValidateKeyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "success", b"success"]) -> None: ...

global___GradientValidateKeyResponse = GradientValidateKeyResponse

@typing.final
class GradientSaveRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/v2/enterprise_console/gradient/save"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GRADIENTKEY_FIELD_NUMBER: builtins.int
    ENTERPRISEUSERID_FIELD_NUMBER: builtins.int
    gradientKey: builtins.str
    enterpriseUserId: builtins.int
    def __init__(
        self,
        *,
        gradientKey: builtins.str = ...,
        enterpriseUserId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["enterpriseUserId", b"enterpriseUserId", "gradientKey", b"gradientKey"]) -> None: ...

global___GradientSaveRequest = GradientSaveRequest

@typing.final
class GradientSaveResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    status: global___GradientIntegrationStatus.ValueType
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        status: global___GradientIntegrationStatus.ValueType = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "status", b"status", "success", b"success"]) -> None: ...

global___GradientSaveResponse = GradientSaveResponse

@typing.final
class GradientRemoveRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/v2/enterprise_console/gradient/remove"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTERPRISEUSERID_FIELD_NUMBER: builtins.int
    enterpriseUserId: builtins.int
    def __init__(
        self,
        *,
        enterpriseUserId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["enterpriseUserId", b"enterpriseUserId"]) -> None: ...

global___GradientRemoveRequest = GradientRemoveRequest

@typing.final
class GradientRemoveResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "success", b"success"]) -> None: ...

global___GradientRemoveResponse = GradientRemoveResponse

@typing.final
class GradientSyncRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/v2/enterprise_console/gradient/sync"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTERPRISEUSERID_FIELD_NUMBER: builtins.int
    enterpriseUserId: builtins.int
    def __init__(
        self,
        *,
        enterpriseUserId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["enterpriseUserId", b"enterpriseUserId"]) -> None: ...

global___GradientSyncRequest = GradientSyncRequest

@typing.final
class GradientSyncResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    status: global___GradientIntegrationStatus.ValueType
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        status: global___GradientIntegrationStatus.ValueType = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "status", b"status", "success", b"success"]) -> None: ...

global___GradientSyncResponse = GradientSyncResponse

@typing.final
class NetPromoterScoreSurveySubmissionRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/v2/enterprise_console/net_promoter_scores"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SURVEY_SCORE_FIELD_NUMBER: builtins.int
    NOTES_FIELD_NUMBER: builtins.int
    survey_score: builtins.int
    notes: builtins.str
    def __init__(
        self,
        *,
        survey_score: builtins.int = ...,
        notes: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["notes", b"notes", "survey_score", b"survey_score"]) -> None: ...

global___NetPromoterScoreSurveySubmissionRequest = NetPromoterScoreSurveySubmissionRequest

@typing.final
class NetPromoterScoreSurveySubmissionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___NetPromoterScoreSurveySubmissionResponse = NetPromoterScoreSurveySubmissionResponse

@typing.final
class NetPromoterScorePopupScheduleRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/v2/enterprise_console/net_promoter_score/popup/schedule"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___NetPromoterScorePopupScheduleRequest = NetPromoterScorePopupScheduleRequest

@typing.final
class NetPromoterScorePopupScheduleResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHOW_POPUP_FIELD_NUMBER: builtins.int
    show_popup: builtins.bool
    def __init__(
        self,
        *,
        show_popup: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["show_popup", b"show_popup"]) -> None: ...

global___NetPromoterScorePopupScheduleResponse = NetPromoterScorePopupScheduleResponse

@typing.final
class NetPromoterScorePopupDismissalRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/v2/enterprise_console/net_promoter_score/popup/dismiss"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___NetPromoterScorePopupDismissalRequest = NetPromoterScorePopupDismissalRequest

@typing.final
class NetPromoterScorePopupDismissalResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___NetPromoterScorePopupDismissalResponse = NetPromoterScorePopupDismissalResponse

@typing.final
class KCMLicenseRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/v2/enterprise_console/kcm/license"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTERPRISEUSERID_FIELD_NUMBER: builtins.int
    enterpriseUserId: builtins.int
    def __init__(
        self,
        *,
        enterpriseUserId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["enterpriseUserId", b"enterpriseUserId"]) -> None: ...

global___KCMLicenseRequest = KCMLicenseRequest

@typing.final
class KCMLicenseResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    message: builtins.str
    def __init__(
        self,
        *,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message"]) -> None: ...

global___KCMLicenseResponse = KCMLicenseResponse

@typing.final
class EventRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/v2/analytics/log_event"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EVENTTYPE_FIELD_NUMBER: builtins.int
    EVENTVALUE_FIELD_NUMBER: builtins.int
    EVENTTIME_FIELD_NUMBER: builtins.int
    ATTRIBUTES_FIELD_NUMBER: builtins.int
    eventType: global___EventType.ValueType
    eventValue: builtins.str
    eventTime: builtins.int
    @property
    def attributes(self) -> google.protobuf.struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        eventType: global___EventType.ValueType = ...,
        eventValue: builtins.str = ...,
        eventTime: builtins.int = ...,
        attributes: google.protobuf.struct_pb2.Struct | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["attributes", b"attributes"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["attributes", b"attributes", "eventTime", b"eventTime", "eventType", b"eventType", "eventValue", b"eventValue"]) -> None: ...

global___EventRequest = EventRequest

@typing.final
class EventsRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/v2/analytics/log_events"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EVENT_FIELD_NUMBER: builtins.int
    @property
    def event(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EventRequest]: ...
    def __init__(
        self,
        *,
        event: collections.abc.Iterable[global___EventRequest] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["event", b"event"]) -> None: ...

global___EventsRequest = EventsRequest

@typing.final
class CustomerCaptureRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/rest/browser_extension/customer_capture"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAGEURL_FIELD_NUMBER: builtins.int
    TREE_FIELD_NUMBER: builtins.int
    HASH_FIELD_NUMBER: builtins.int
    IMAGE_FIELD_NUMBER: builtins.int
    PAGELOADTIME_FIELD_NUMBER: builtins.int
    KEYID_FIELD_NUMBER: builtins.int
    TEST_FIELD_NUMBER: builtins.int
    ISSUETYPE_FIELD_NUMBER: builtins.int
    NOTES_FIELD_NUMBER: builtins.int
    pageUrl: builtins.str
    """encrypted"""
    tree: builtins.str
    """JSON -> encrypted"""
    hash: builtins.str
    image: builtins.str
    """base64 + encrypted"""
    pageLoadTime: builtins.str
    """number -> encrypted"""
    keyId: builtins.str
    """string (id of public key used to encrypt, so only the Fixinator internal tool can decrypt the payload contents)"""
    test: builtins.bool
    """set by BI"""
    issueType: builtins.str
    notes: builtins.str
    """base64 + encrypted"""
    def __init__(
        self,
        *,
        pageUrl: builtins.str = ...,
        tree: builtins.str = ...,
        hash: builtins.str = ...,
        image: builtins.str = ...,
        pageLoadTime: builtins.str = ...,
        keyId: builtins.str = ...,
        test: builtins.bool = ...,
        issueType: builtins.str = ...,
        notes: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["hash", b"hash", "image", b"image", "issueType", b"issueType", "keyId", b"keyId", "notes", b"notes", "pageLoadTime", b"pageLoadTime", "pageUrl", b"pageUrl", "test", b"test", "tree", b"tree"]) -> None: ...

global___CustomerCaptureRequest = CustomerCaptureRequest

@typing.final
class CustomerCaptureResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___CustomerCaptureResponse = CustomerCaptureResponse

@typing.final
class Error(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ExtrasEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    EXTRAS_FIELD_NUMBER: builtins.int
    code: builtins.str
    message: builtins.str
    @property
    def extras(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        code: builtins.str = ...,
        message: builtins.str = ...,
        extras: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["code", b"code", "extras", b"extras", "message", b"message"]) -> None: ...

global___Error = Error

@typing.final
class QuotePurchase(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUOTETOTAL_FIELD_NUMBER: builtins.int
    INCLUDEDTAX_FIELD_NUMBER: builtins.int
    INCLUDEDOTHERADDONS_FIELD_NUMBER: builtins.int
    TAXAMOUNT_FIELD_NUMBER: builtins.int
    TAXLABEL_FIELD_NUMBER: builtins.int
    quoteTotal: builtins.float
    includedTax: builtins.bool
    includedOtherAddons: builtins.bool
    taxAmount: builtins.float
    taxLabel: builtins.str
    def __init__(
        self,
        *,
        quoteTotal: builtins.float = ...,
        includedTax: builtins.bool = ...,
        includedOtherAddons: builtins.bool = ...,
        taxAmount: builtins.float = ...,
        taxLabel: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["includedOtherAddons", b"includedOtherAddons", "includedTax", b"includedTax", "quoteTotal", b"quoteTotal", "taxAmount", b"taxAmount", "taxLabel", b"taxLabel"]) -> None: ...

global___QuotePurchase = QuotePurchase

@typing.final
class UpgradeLicenseStatusRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/v2/enterprise_console/upgrade_license/status"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___UpgradeLicenseStatusRequest = UpgradeLicenseStatusRequest

@typing.final
class UpgradeLicenseStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALLOWPURCHASEFROMCONSOLE_FIELD_NUMBER: builtins.int
    CHECKOUTLINK_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    allowPurchaseFromConsole: builtins.bool
    checkoutLink: builtins.str
    @property
    def error(self) -> global___Error: ...
    def __init__(
        self,
        *,
        allowPurchaseFromConsole: builtins.bool = ...,
        checkoutLink: builtins.str = ...,
        error: global___Error | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["error", b"error"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["allowPurchaseFromConsole", b"allowPurchaseFromConsole", "checkoutLink", b"checkoutLink", "error", b"error"]) -> None: ...

global___UpgradeLicenseStatusResponse = UpgradeLicenseStatusResponse

@typing.final
class UpgradeLicenseQuotePurchaseRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/v2/enterprise_console/upgrade_license/quote_purchase"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRODUCTTYPE_FIELD_NUMBER: builtins.int
    QUANTITY_FIELD_NUMBER: builtins.int
    productType: global___PurchaseProductType.ValueType
    quantity: builtins.int
    """quantity is set only for adding base plan users or PAM users"""
    def __init__(
        self,
        *,
        productType: global___PurchaseProductType.ValueType = ...,
        quantity: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["productType", b"productType", "quantity", b"quantity"]) -> None: ...

global___UpgradeLicenseQuotePurchaseRequest = UpgradeLicenseQuotePurchaseRequest

@typing.final
class UpgradeLicenseQuotePurchaseResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    QUOTEPURCHASE_FIELD_NUMBER: builtins.int
    VIEWSUMMARYLINK_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    success: builtins.bool
    viewSummaryLink: builtins.str
    """checkout link with url params"""
    @property
    def quotePurchase(self) -> global___QuotePurchase: ...
    @property
    def error(self) -> global___Error:
        """available only if success is false"""

    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        quotePurchase: global___QuotePurchase | None = ...,
        viewSummaryLink: builtins.str = ...,
        error: global___Error | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["error", b"error", "quotePurchase", b"quotePurchase"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "quotePurchase", b"quotePurchase", "success", b"success", "viewSummaryLink", b"viewSummaryLink"]) -> None: ...

global___UpgradeLicenseQuotePurchaseResponse = UpgradeLicenseQuotePurchaseResponse

@typing.final
class UpgradeLicenseCompletePurchaseRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/v2/enterprise_console/upgrade_license/complete_purchase"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRODUCTTYPE_FIELD_NUMBER: builtins.int
    QUANTITY_FIELD_NUMBER: builtins.int
    QUOTEPURCHASE_FIELD_NUMBER: builtins.int
    productType: global___PurchaseProductType.ValueType
    quantity: builtins.int
    """quantity is set only for adding base plan users or PAM users"""
    @property
    def quotePurchase(self) -> global___QuotePurchase: ...
    def __init__(
        self,
        *,
        productType: global___PurchaseProductType.ValueType = ...,
        quantity: builtins.int = ...,
        quotePurchase: global___QuotePurchase | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["quotePurchase", b"quotePurchase"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["productType", b"productType", "quantity", b"quantity", "quotePurchase", b"quotePurchase"]) -> None: ...

global___UpgradeLicenseCompletePurchaseRequest = UpgradeLicenseCompletePurchaseRequest

@typing.final
class UpgradeLicenseCompletePurchaseResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    INVOICENUMBER_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    QUOTEPURCHASE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    invoiceNumber: builtins.str
    @property
    def error(self) -> global___Error: ...
    @property
    def quotePurchase(self) -> global___QuotePurchase:
        """quotePurchase is available only if success is false and error.code is quoteMismatch"""

    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        invoiceNumber: builtins.str = ...,
        error: global___Error | None = ...,
        quotePurchase: global___QuotePurchase | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["error", b"error", "quotePurchase", b"quotePurchase"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "invoiceNumber", b"invoiceNumber", "quotePurchase", b"quotePurchase", "success", b"success"]) -> None: ...

global___UpgradeLicenseCompletePurchaseResponse = UpgradeLicenseCompletePurchaseResponse

@typing.final
class EnterpriseBasePlan(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _EnterpriseBasePlanVersion:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _EnterpriseBasePlanVersionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[EnterpriseBasePlan._EnterpriseBasePlanVersion.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: EnterpriseBasePlan._EnterpriseBasePlanVersion.ValueType  # 0
        BUSINESS_STARTER: EnterpriseBasePlan._EnterpriseBasePlanVersion.ValueType  # 1
        BUSINESS: EnterpriseBasePlan._EnterpriseBasePlanVersion.ValueType  # 2
        ENTERPRISE: EnterpriseBasePlan._EnterpriseBasePlanVersion.ValueType  # 3

    class EnterpriseBasePlanVersion(_EnterpriseBasePlanVersion, metaclass=_EnterpriseBasePlanVersionEnumTypeWrapper): ...
    UNKNOWN: EnterpriseBasePlan.EnterpriseBasePlanVersion.ValueType  # 0
    BUSINESS_STARTER: EnterpriseBasePlan.EnterpriseBasePlanVersion.ValueType  # 1
    BUSINESS: EnterpriseBasePlan.EnterpriseBasePlanVersion.ValueType  # 2
    ENTERPRISE: EnterpriseBasePlan.EnterpriseBasePlanVersion.ValueType  # 3

    BASEPLANVERSION_FIELD_NUMBER: builtins.int
    COST_FIELD_NUMBER: builtins.int
    baseplanVersion: global___EnterpriseBasePlan.EnterpriseBasePlanVersion.ValueType
    @property
    def cost(self) -> global___Cost: ...
    def __init__(
        self,
        *,
        baseplanVersion: global___EnterpriseBasePlan.EnterpriseBasePlanVersion.ValueType = ...,
        cost: global___Cost | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["cost", b"cost"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["baseplanVersion", b"baseplanVersion", "cost", b"cost"]) -> None: ...

global___EnterpriseBasePlan = EnterpriseBasePlan

@typing.final
class SubscriptionEnterprisePricingRequest(google.protobuf.message.Message):
    """-- POST: /bi_api/v2/console/subscription/enterprise_pricing"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___SubscriptionEnterprisePricingRequest = SubscriptionEnterprisePricingRequest

@typing.final
class SubscriptionEnterprisePricingResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BASEPLANS_FIELD_NUMBER: builtins.int
    ADDONS_FIELD_NUMBER: builtins.int
    FILEPLANS_FIELD_NUMBER: builtins.int
    @property
    def basePlans(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EnterpriseBasePlan]: ...
    @property
    def addons(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Addon]: ...
    @property
    def filePlans(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FilePlan]: ...
    def __init__(
        self,
        *,
        basePlans: collections.abc.Iterable[global___EnterpriseBasePlan] | None = ...,
        addons: collections.abc.Iterable[global___Addon] | None = ...,
        filePlans: collections.abc.Iterable[global___FilePlan] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["addons", b"addons", "basePlans", b"basePlans", "filePlans", b"filePlans"]) -> None: ...

global___SubscriptionEnterprisePricingResponse = SubscriptionEnterprisePricingResponse
