"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _BreachWatchInfoType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BreachWatchInfoTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BreachWatchInfoType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RECORD: _BreachWatchInfoType.ValueType  # 0
    """note: this also is used for master password where the recordUid is blank"""
    ALTERNATE_PASSWORD: _BreachWatchInfoType.ValueType  # 1
    """for any user_auth passwords, including the passwords used through Pythia"""

class BreachWatchInfoType(_BreachWatchInfoType, metaclass=_BreachWatchInfoTypeEnumTypeWrapper): ...

RECORD: BreachWatchInfoType.ValueType  # 0
"""note: this also is used for master password where the recordUid is blank"""
ALTERNATE_PASSWORD: BreachWatchInfoType.ValueType  # 1
"""for any user_auth passwords, including the passwords used through Pythia"""
global___BreachWatchInfoType = BreachWatchInfoType

class _BWStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BWStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BWStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GOOD: _BWStatus.ValueType  # 0
    CHANGED: _BWStatus.ValueType  # 1
    WEAK: _BWStatus.ValueType  # 2
    BREACHED: _BWStatus.ValueType  # 3
    IGNORE: _BWStatus.ValueType  # 4

class BWStatus(_BWStatus, metaclass=_BWStatusEnumTypeWrapper): ...

GOOD: BWStatus.ValueType  # 0
CHANGED: BWStatus.ValueType  # 1
WEAK: BWStatus.ValueType  # 2
BREACHED: BWStatus.ValueType  # 3
IGNORE: BWStatus.ValueType  # 4
global___BWStatus = BWStatus

@typing.final
class BreachWatchUpdateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BREACHWATCHRECORDREQUEST_FIELD_NUMBER: builtins.int
    ENCRYPTEDDATA_FIELD_NUMBER: builtins.int
    encryptedData: builtins.bytes
    @property
    def breachWatchRecordRequest(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BreachWatchRecordRequest]: ...
    def __init__(
        self,
        *,
        breachWatchRecordRequest: collections.abc.Iterable[global___BreachWatchRecordRequest] | None = ...,
        encryptedData: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["breachWatchRecordRequest", b"breachWatchRecordRequest", "encryptedData", b"encryptedData"]) -> None: ...

global___BreachWatchUpdateRequest = BreachWatchUpdateRequest

@typing.final
class BreachWatchRecordRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORDUID_FIELD_NUMBER: builtins.int
    ENCRYPTEDDATA_FIELD_NUMBER: builtins.int
    BREACHWATCHINFOTYPE_FIELD_NUMBER: builtins.int
    UPDATEUSERWHOSCANNED_FIELD_NUMBER: builtins.int
    recordUid: builtins.bytes
    """if you store the recordUid as a string this is URLSafeBase64.decode(recordUid)"""
    encryptedData: builtins.bytes
    """This is a BreachWatchRecordData message encrypted with the record key"""
    breachWatchInfoType: global___BreachWatchInfoType.ValueType
    updateUserWhoScanned: builtins.bool
    def __init__(
        self,
        *,
        recordUid: builtins.bytes = ...,
        encryptedData: builtins.bytes = ...,
        breachWatchInfoType: global___BreachWatchInfoType.ValueType = ...,
        updateUserWhoScanned: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["breachWatchInfoType", b"breachWatchInfoType", "encryptedData", b"encryptedData", "recordUid", b"recordUid", "updateUserWhoScanned", b"updateUserWhoScanned"]) -> None: ...

global___BreachWatchRecordRequest = BreachWatchRecordRequest

@typing.final
class BreachWatchData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PASSWORDS_FIELD_NUMBER: builtins.int
    EMAILS_FIELD_NUMBER: builtins.int
    DOMAINS_FIELD_NUMBER: builtins.int
    @property
    def passwords(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BWPassword]: ...
    @property
    def emails(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BWPassword]: ...
    @property
    def domains(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BWPassword]: ...
    def __init__(
        self,
        *,
        passwords: collections.abc.Iterable[global___BWPassword] | None = ...,
        emails: collections.abc.Iterable[global___BWPassword] | None = ...,
        domains: collections.abc.Iterable[global___BWPassword] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["domains", b"domains", "emails", b"emails", "passwords", b"passwords"]) -> None: ...

global___BreachWatchData = BreachWatchData

@typing.final
class BWPassword(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    RESOLVED_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    EUID_FIELD_NUMBER: builtins.int
    value: builtins.str
    """the original password"""
    resolved: builtins.int
    """time stamp for when it was resolved"""
    status: global___BWStatus.ValueType
    euid: builtins.bytes
    """if breached this is empty, else this is the value returned by keeperapp after submission"""
    def __init__(
        self,
        *,
        value: builtins.str = ...,
        resolved: builtins.int = ...,
        status: global___BWStatus.ValueType = ...,
        euid: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["euid", b"euid", "resolved", b"resolved", "status", b"status", "value", b"value"]) -> None: ...

global___BWPassword = BWPassword
