"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import record_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _RecordType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RecordTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RecordType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    password: _RecordType.ValueType  # 0

class RecordType(_RecordType, metaclass=_RecordTypeEnumTypeWrapper): ...

password: RecordType.ValueType  # 0
global___RecordType = RecordType

class _FolderType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _FolderTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_FolderType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    default_folder: _FolderType.ValueType  # 0
    user_folder: _FolderType.ValueType  # 1
    shared_folder: _FolderType.ValueType  # 2
    shared_folder_folder: _FolderType.ValueType  # 3

class FolderType(_FolderType, metaclass=_FolderTypeEnumTypeWrapper): ...

default_folder: FolderType.ValueType  # 0
user_folder: FolderType.ValueType  # 1
shared_folder: FolderType.ValueType  # 2
shared_folder_folder: FolderType.ValueType  # 3
global___FolderType = FolderType

class _EncryptedKeyType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EncryptedKeyTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EncryptedKeyType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    no_key: _EncryptedKeyType.ValueType  # 0
    encrypted_by_data_key: _EncryptedKeyType.ValueType  # 1
    encrypted_by_public_key: _EncryptedKeyType.ValueType  # 2
    encrypted_by_data_key_gcm: _EncryptedKeyType.ValueType  # 3
    encrypted_by_public_key_ecc: _EncryptedKeyType.ValueType  # 4

class EncryptedKeyType(_EncryptedKeyType, metaclass=_EncryptedKeyTypeEnumTypeWrapper): ...

no_key: EncryptedKeyType.ValueType  # 0
encrypted_by_data_key: EncryptedKeyType.ValueType  # 1
encrypted_by_public_key: EncryptedKeyType.ValueType  # 2
encrypted_by_data_key_gcm: EncryptedKeyType.ValueType  # 3
encrypted_by_public_key_ecc: EncryptedKeyType.ValueType  # 4
global___EncryptedKeyType = EncryptedKeyType

class _SetBooleanValue:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SetBooleanValueEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SetBooleanValue.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BOOLEAN_NO_CHANGE: _SetBooleanValue.ValueType  # 0
    BOOLEAN_TRUE: _SetBooleanValue.ValueType  # 1
    BOOLEAN_FALSE: _SetBooleanValue.ValueType  # 2

class SetBooleanValue(_SetBooleanValue, metaclass=_SetBooleanValueEnumTypeWrapper): ...

BOOLEAN_NO_CHANGE: SetBooleanValue.ValueType  # 0
BOOLEAN_TRUE: SetBooleanValue.ValueType  # 1
BOOLEAN_FALSE: SetBooleanValue.ValueType  # 2
global___SetBooleanValue = SetBooleanValue

@typing.final
class EncryptedDataKey(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENCRYPTEDKEY_FIELD_NUMBER: builtins.int
    ENCRYPTEDKEYTYPE_FIELD_NUMBER: builtins.int
    encryptedKey: builtins.bytes
    encryptedKeyType: global___EncryptedKeyType.ValueType
    def __init__(
        self,
        *,
        encryptedKey: builtins.bytes = ...,
        encryptedKeyType: global___EncryptedKeyType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["encryptedKey", b"encryptedKey", "encryptedKeyType", b"encryptedKeyType"]) -> None: ...

global___EncryptedDataKey = EncryptedDataKey

@typing.final
class SharedFolderRecordData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOLDERUID_FIELD_NUMBER: builtins.int
    RECORDUID_FIELD_NUMBER: builtins.int
    USERID_FIELD_NUMBER: builtins.int
    ENCRYPTEDDATAKEY_FIELD_NUMBER: builtins.int
    folderUid: builtins.bytes
    recordUid: builtins.bytes
    userId: builtins.int
    @property
    def encryptedDataKey(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EncryptedDataKey]:
        """in the order of encryptedRecordKey, encryptedSharedFolderKey and optional encryptedTeamKey"""

    def __init__(
        self,
        *,
        folderUid: builtins.bytes = ...,
        recordUid: builtins.bytes = ...,
        userId: builtins.int = ...,
        encryptedDataKey: collections.abc.Iterable[global___EncryptedDataKey] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["encryptedDataKey", b"encryptedDataKey", "folderUid", b"folderUid", "recordUid", b"recordUid", "userId", b"userId"]) -> None: ...

global___SharedFolderRecordData = SharedFolderRecordData

@typing.final
class SharedFolderRecordDataList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHAREDFOLDERRECORDDATA_FIELD_NUMBER: builtins.int
    @property
    def sharedFolderRecordData(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SharedFolderRecordData]: ...
    def __init__(
        self,
        *,
        sharedFolderRecordData: collections.abc.Iterable[global___SharedFolderRecordData] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["sharedFolderRecordData", b"sharedFolderRecordData"]) -> None: ...

global___SharedFolderRecordDataList = SharedFolderRecordDataList

@typing.final
class SharedFolderRecordFix(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOLDERUID_FIELD_NUMBER: builtins.int
    RECORDUID_FIELD_NUMBER: builtins.int
    ENCRYPTEDRECORDFOLDERKEY_FIELD_NUMBER: builtins.int
    folderUid: builtins.bytes
    recordUid: builtins.bytes
    encryptedRecordFolderKey: builtins.bytes
    def __init__(
        self,
        *,
        folderUid: builtins.bytes = ...,
        recordUid: builtins.bytes = ...,
        encryptedRecordFolderKey: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["encryptedRecordFolderKey", b"encryptedRecordFolderKey", "folderUid", b"folderUid", "recordUid", b"recordUid"]) -> None: ...

global___SharedFolderRecordFix = SharedFolderRecordFix

@typing.final
class SharedFolderRecordFixList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHAREDFOLDERRECORDFIX_FIELD_NUMBER: builtins.int
    @property
    def sharedFolderRecordFix(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SharedFolderRecordFix]: ...
    def __init__(
        self,
        *,
        sharedFolderRecordFix: collections.abc.Iterable[global___SharedFolderRecordFix] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["sharedFolderRecordFix", b"sharedFolderRecordFix"]) -> None: ...

global___SharedFolderRecordFixList = SharedFolderRecordFixList

@typing.final
class RecordRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORDUID_FIELD_NUMBER: builtins.int
    RECORDTYPE_FIELD_NUMBER: builtins.int
    RECORDDATA_FIELD_NUMBER: builtins.int
    ENCRYPTEDRECORDKEY_FIELD_NUMBER: builtins.int
    FOLDERTYPE_FIELD_NUMBER: builtins.int
    HOWLONGAGO_FIELD_NUMBER: builtins.int
    FOLDERUID_FIELD_NUMBER: builtins.int
    ENCRYPTEDRECORDFOLDERKEY_FIELD_NUMBER: builtins.int
    EXTRA_FIELD_NUMBER: builtins.int
    NONSHAREDDATA_FIELD_NUMBER: builtins.int
    FILEIDS_FIELD_NUMBER: builtins.int
    recordUid: builtins.bytes
    recordType: global___RecordType.ValueType
    recordData: builtins.bytes
    encryptedRecordKey: builtins.bytes
    folderType: global___FolderType.ValueType
    howLongAgo: builtins.int
    folderUid: builtins.bytes
    encryptedRecordFolderKey: builtins.bytes
    extra: builtins.bytes
    nonSharedData: builtins.bytes
    @property
    def fileIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        recordUid: builtins.bytes = ...,
        recordType: global___RecordType.ValueType = ...,
        recordData: builtins.bytes = ...,
        encryptedRecordKey: builtins.bytes = ...,
        folderType: global___FolderType.ValueType = ...,
        howLongAgo: builtins.int = ...,
        folderUid: builtins.bytes = ...,
        encryptedRecordFolderKey: builtins.bytes = ...,
        extra: builtins.bytes = ...,
        nonSharedData: builtins.bytes = ...,
        fileIds: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["encryptedRecordFolderKey", b"encryptedRecordFolderKey", "encryptedRecordKey", b"encryptedRecordKey", "extra", b"extra", "fileIds", b"fileIds", "folderType", b"folderType", "folderUid", b"folderUid", "howLongAgo", b"howLongAgo", "nonSharedData", b"nonSharedData", "recordData", b"recordData", "recordType", b"recordType", "recordUid", b"recordUid"]) -> None: ...

global___RecordRequest = RecordRequest

@typing.final
class RecordResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORDUID_FIELD_NUMBER: builtins.int
    REVISION_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    recordUid: builtins.bytes
    revision: builtins.int
    status: builtins.str
    def __init__(
        self,
        *,
        recordUid: builtins.bytes = ...,
        revision: builtins.int = ...,
        status: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["recordUid", b"recordUid", "revision", b"revision", "status", b"status"]) -> None: ...

global___RecordResponse = RecordResponse

@typing.final
class SharedFolderFields(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENCRYPTEDFOLDERNAME_FIELD_NUMBER: builtins.int
    MANAGEUSERS_FIELD_NUMBER: builtins.int
    MANAGERECORDS_FIELD_NUMBER: builtins.int
    CANEDIT_FIELD_NUMBER: builtins.int
    CANSHARE_FIELD_NUMBER: builtins.int
    encryptedFolderName: builtins.bytes
    manageUsers: builtins.bool
    manageRecords: builtins.bool
    canEdit: builtins.bool
    canShare: builtins.bool
    def __init__(
        self,
        *,
        encryptedFolderName: builtins.bytes = ...,
        manageUsers: builtins.bool = ...,
        manageRecords: builtins.bool = ...,
        canEdit: builtins.bool = ...,
        canShare: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["canEdit", b"canEdit", "canShare", b"canShare", "encryptedFolderName", b"encryptedFolderName", "manageRecords", b"manageRecords", "manageUsers", b"manageUsers"]) -> None: ...

global___SharedFolderFields = SharedFolderFields

@typing.final
class SharedFolderFolderFields(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHAREDFOLDERUID_FIELD_NUMBER: builtins.int
    sharedFolderUid: builtins.bytes
    def __init__(
        self,
        *,
        sharedFolderUid: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["sharedFolderUid", b"sharedFolderUid"]) -> None: ...

global___SharedFolderFolderFields = SharedFolderFolderFields

@typing.final
class FolderRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOLDERUID_FIELD_NUMBER: builtins.int
    FOLDERTYPE_FIELD_NUMBER: builtins.int
    PARENTFOLDERUID_FIELD_NUMBER: builtins.int
    FOLDERDATA_FIELD_NUMBER: builtins.int
    ENCRYPTEDFOLDERKEY_FIELD_NUMBER: builtins.int
    SHAREDFOLDERFIELDS_FIELD_NUMBER: builtins.int
    SHAREDFOLDERFOLDERFIELDS_FIELD_NUMBER: builtins.int
    folderUid: builtins.bytes
    folderType: global___FolderType.ValueType
    parentFolderUid: builtins.bytes
    folderData: builtins.bytes
    encryptedFolderKey: builtins.bytes
    @property
    def sharedFolderFields(self) -> global___SharedFolderFields: ...
    @property
    def sharedFolderFolderFields(self) -> global___SharedFolderFolderFields: ...
    def __init__(
        self,
        *,
        folderUid: builtins.bytes = ...,
        folderType: global___FolderType.ValueType = ...,
        parentFolderUid: builtins.bytes = ...,
        folderData: builtins.bytes = ...,
        encryptedFolderKey: builtins.bytes = ...,
        sharedFolderFields: global___SharedFolderFields | None = ...,
        sharedFolderFolderFields: global___SharedFolderFolderFields | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["sharedFolderFields", b"sharedFolderFields", "sharedFolderFolderFields", b"sharedFolderFolderFields"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["encryptedFolderKey", b"encryptedFolderKey", "folderData", b"folderData", "folderType", b"folderType", "folderUid", b"folderUid", "parentFolderUid", b"parentFolderUid", "sharedFolderFields", b"sharedFolderFields", "sharedFolderFolderFields", b"sharedFolderFolderFields"]) -> None: ...

global___FolderRequest = FolderRequest

@typing.final
class FolderResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOLDERUID_FIELD_NUMBER: builtins.int
    REVISION_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    folderUid: builtins.bytes
    revision: builtins.int
    status: builtins.str
    def __init__(
        self,
        *,
        folderUid: builtins.bytes = ...,
        revision: builtins.int = ...,
        status: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["folderUid", b"folderUid", "revision", b"revision", "status", b"status"]) -> None: ...

global___FolderResponse = FolderResponse

@typing.final
class ImportFolderRecordRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOLDERREQUEST_FIELD_NUMBER: builtins.int
    RECORDREQUEST_FIELD_NUMBER: builtins.int
    @property
    def folderRequest(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FolderRequest]: ...
    @property
    def recordRequest(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RecordRequest]: ...
    def __init__(
        self,
        *,
        folderRequest: collections.abc.Iterable[global___FolderRequest] | None = ...,
        recordRequest: collections.abc.Iterable[global___RecordRequest] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["folderRequest", b"folderRequest", "recordRequest", b"recordRequest"]) -> None: ...

global___ImportFolderRecordRequest = ImportFolderRecordRequest

@typing.final
class ImportFolderRecordResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOLDERRESPONSE_FIELD_NUMBER: builtins.int
    RECORDRESPONSE_FIELD_NUMBER: builtins.int
    @property
    def folderResponse(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FolderResponse]: ...
    @property
    def recordResponse(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RecordResponse]: ...
    def __init__(
        self,
        *,
        folderResponse: collections.abc.Iterable[global___FolderResponse] | None = ...,
        recordResponse: collections.abc.Iterable[global___RecordResponse] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["folderResponse", b"folderResponse", "recordResponse", b"recordResponse"]) -> None: ...

global___ImportFolderRecordResponse = ImportFolderRecordResponse

@typing.final
class SharedFolderUpdateRecord(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORDUID_FIELD_NUMBER: builtins.int
    SHAREDFOLDERUID_FIELD_NUMBER: builtins.int
    TEAMUID_FIELD_NUMBER: builtins.int
    CANEDIT_FIELD_NUMBER: builtins.int
    CANSHARE_FIELD_NUMBER: builtins.int
    ENCRYPTEDRECORDKEY_FIELD_NUMBER: builtins.int
    REVISION_FIELD_NUMBER: builtins.int
    EXPIRATION_FIELD_NUMBER: builtins.int
    TIMERNOTIFICATIONTYPE_FIELD_NUMBER: builtins.int
    ROTATEONEXPIRATION_FIELD_NUMBER: builtins.int
    recordUid: builtins.bytes
    sharedFolderUid: builtins.bytes
    """Only used when adding a record, or updating the permission to a record"""
    teamUid: builtins.bytes
    """Only used when adding a record, or updating the permission to a record"""
    canEdit: global___SetBooleanValue.ValueType
    canShare: global___SetBooleanValue.ValueType
    encryptedRecordKey: builtins.bytes
    """record key encrypted with the shared folder key"""
    revision: builtins.int
    expiration: builtins.int
    timerNotificationType: record_pb2.TimerNotificationType.ValueType
    rotateOnExpiration: builtins.bool
    def __init__(
        self,
        *,
        recordUid: builtins.bytes = ...,
        sharedFolderUid: builtins.bytes = ...,
        teamUid: builtins.bytes = ...,
        canEdit: global___SetBooleanValue.ValueType = ...,
        canShare: global___SetBooleanValue.ValueType = ...,
        encryptedRecordKey: builtins.bytes = ...,
        revision: builtins.int = ...,
        expiration: builtins.int = ...,
        timerNotificationType: record_pb2.TimerNotificationType.ValueType = ...,
        rotateOnExpiration: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["canEdit", b"canEdit", "canShare", b"canShare", "encryptedRecordKey", b"encryptedRecordKey", "expiration", b"expiration", "recordUid", b"recordUid", "revision", b"revision", "rotateOnExpiration", b"rotateOnExpiration", "sharedFolderUid", b"sharedFolderUid", "teamUid", b"teamUid", "timerNotificationType", b"timerNotificationType"]) -> None: ...

global___SharedFolderUpdateRecord = SharedFolderUpdateRecord

@typing.final
class SharedFolderUpdateUser(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    MANAGEUSERS_FIELD_NUMBER: builtins.int
    MANAGERECORDS_FIELD_NUMBER: builtins.int
    SHAREDFOLDERKEY_FIELD_NUMBER: builtins.int
    EXPIRATION_FIELD_NUMBER: builtins.int
    TIMERNOTIFICATIONTYPE_FIELD_NUMBER: builtins.int
    TYPEDSHAREDFOLDERKEY_FIELD_NUMBER: builtins.int
    ROTATEONEXPIRATION_FIELD_NUMBER: builtins.int
    username: builtins.str
    manageUsers: global___SetBooleanValue.ValueType
    manageRecords: global___SetBooleanValue.ValueType
    sharedFolderKey: builtins.bytes
    """shared folder AES key encrypted with user's "key" (for the caller, the user's data key, for a different user, the user's public key) - use typedSharedFolderKey instead"""
    expiration: builtins.int
    timerNotificationType: record_pb2.TimerNotificationType.ValueType
    rotateOnExpiration: builtins.bool
    @property
    def typedSharedFolderKey(self) -> global___EncryptedDataKey: ...
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        manageUsers: global___SetBooleanValue.ValueType = ...,
        manageRecords: global___SetBooleanValue.ValueType = ...,
        sharedFolderKey: builtins.bytes = ...,
        expiration: builtins.int = ...,
        timerNotificationType: record_pb2.TimerNotificationType.ValueType = ...,
        typedSharedFolderKey: global___EncryptedDataKey | None = ...,
        rotateOnExpiration: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["typedSharedFolderKey", b"typedSharedFolderKey"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["expiration", b"expiration", "manageRecords", b"manageRecords", "manageUsers", b"manageUsers", "rotateOnExpiration", b"rotateOnExpiration", "sharedFolderKey", b"sharedFolderKey", "timerNotificationType", b"timerNotificationType", "typedSharedFolderKey", b"typedSharedFolderKey", "username", b"username"]) -> None: ...

global___SharedFolderUpdateUser = SharedFolderUpdateUser

@typing.final
class SharedFolderUpdateTeam(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TEAMUID_FIELD_NUMBER: builtins.int
    MANAGEUSERS_FIELD_NUMBER: builtins.int
    MANAGERECORDS_FIELD_NUMBER: builtins.int
    SHAREDFOLDERKEY_FIELD_NUMBER: builtins.int
    EXPIRATION_FIELD_NUMBER: builtins.int
    TIMERNOTIFICATIONTYPE_FIELD_NUMBER: builtins.int
    TYPEDSHAREDFOLDERKEY_FIELD_NUMBER: builtins.int
    ROTATEONEXPIRATION_FIELD_NUMBER: builtins.int
    teamUid: builtins.bytes
    manageUsers: builtins.bool
    manageRecords: builtins.bool
    sharedFolderKey: builtins.bytes
    """shared folder AES key encrypted with the team key retrieved from team_get_keys, for team member, which is team key; for a non member, the team's public key - use typedSharedFolderKey instead"""
    expiration: builtins.int
    timerNotificationType: record_pb2.TimerNotificationType.ValueType
    rotateOnExpiration: builtins.bool
    @property
    def typedSharedFolderKey(self) -> global___EncryptedDataKey: ...
    def __init__(
        self,
        *,
        teamUid: builtins.bytes = ...,
        manageUsers: builtins.bool = ...,
        manageRecords: builtins.bool = ...,
        sharedFolderKey: builtins.bytes = ...,
        expiration: builtins.int = ...,
        timerNotificationType: record_pb2.TimerNotificationType.ValueType = ...,
        typedSharedFolderKey: global___EncryptedDataKey | None = ...,
        rotateOnExpiration: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["typedSharedFolderKey", b"typedSharedFolderKey"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["expiration", b"expiration", "manageRecords", b"manageRecords", "manageUsers", b"manageUsers", "rotateOnExpiration", b"rotateOnExpiration", "sharedFolderKey", b"sharedFolderKey", "teamUid", b"teamUid", "timerNotificationType", b"timerNotificationType", "typedSharedFolderKey", b"typedSharedFolderKey"]) -> None: ...

global___SharedFolderUpdateTeam = SharedFolderUpdateTeam

@typing.final
class SharedFolderUpdateV3Request(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHAREDFOLDERUPDATEOPERATION_DONT_USE_FIELD_NUMBER: builtins.int
    SHAREDFOLDERUID_FIELD_NUMBER: builtins.int
    ENCRYPTEDSHAREDFOLDERNAME_FIELD_NUMBER: builtins.int
    REVISION_FIELD_NUMBER: builtins.int
    FORCEUPDATE_FIELD_NUMBER: builtins.int
    FROMTEAMUID_FIELD_NUMBER: builtins.int
    DEFAULTMANAGEUSERS_FIELD_NUMBER: builtins.int
    DEFAULTMANAGERECORDS_FIELD_NUMBER: builtins.int
    DEFAULTCANEDIT_FIELD_NUMBER: builtins.int
    DEFAULTCANSHARE_FIELD_NUMBER: builtins.int
    SHAREDFOLDERADDRECORD_FIELD_NUMBER: builtins.int
    SHAREDFOLDERADDUSER_FIELD_NUMBER: builtins.int
    SHAREDFOLDERADDTEAM_FIELD_NUMBER: builtins.int
    SHAREDFOLDERUPDATERECORD_FIELD_NUMBER: builtins.int
    SHAREDFOLDERUPDATEUSER_FIELD_NUMBER: builtins.int
    SHAREDFOLDERUPDATETEAM_FIELD_NUMBER: builtins.int
    SHAREDFOLDERREMOVERECORD_FIELD_NUMBER: builtins.int
    SHAREDFOLDERREMOVEUSER_FIELD_NUMBER: builtins.int
    SHAREDFOLDERREMOVETEAM_FIELD_NUMBER: builtins.int
    SHAREDFOLDEROWNER_FIELD_NUMBER: builtins.int
    sharedFolderUpdateOperation_dont_use: builtins.int
    """obsolete field. we only use this request for shared folder update now."""
    sharedFolderUid: builtins.bytes
    """required"""
    encryptedSharedFolderName: builtins.bytes
    """shared folder name encrypted with the shared folder key"""
    revision: builtins.int
    """clientSharedFolderRevision"""
    forceUpdate: builtins.bool
    """true if the requestor does not want the revision to be validated for out of sync; either force_update must be true, or revision is required"""
    fromTeamUid: builtins.bytes
    """for update/delete only; this is the team that gives you the permission to perform the operations you are trying to perform"""
    defaultManageUsers: global___SetBooleanValue.ValueType
    defaultManageRecords: global___SetBooleanValue.ValueType
    defaultCanEdit: global___SetBooleanValue.ValueType
    defaultCanShare: global___SetBooleanValue.ValueType
    sharedFolderOwner: builtins.str
    """should have a sharing relationship w/ the calling user; ""=No Change(default); "delete"=unset"""
    @property
    def sharedFolderAddRecord(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SharedFolderUpdateRecord]: ...
    @property
    def sharedFolderAddUser(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SharedFolderUpdateUser]: ...
    @property
    def sharedFolderAddTeam(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SharedFolderUpdateTeam]: ...
    @property
    def sharedFolderUpdateRecord(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SharedFolderUpdateRecord]: ...
    @property
    def sharedFolderUpdateUser(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SharedFolderUpdateUser]: ...
    @property
    def sharedFolderUpdateTeam(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SharedFolderUpdateTeam]: ...
    @property
    def sharedFolderRemoveRecord(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    @property
    def sharedFolderRemoveUser(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def sharedFolderRemoveTeam(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        sharedFolderUpdateOperation_dont_use: builtins.int = ...,
        sharedFolderUid: builtins.bytes = ...,
        encryptedSharedFolderName: builtins.bytes = ...,
        revision: builtins.int = ...,
        forceUpdate: builtins.bool = ...,
        fromTeamUid: builtins.bytes = ...,
        defaultManageUsers: global___SetBooleanValue.ValueType = ...,
        defaultManageRecords: global___SetBooleanValue.ValueType = ...,
        defaultCanEdit: global___SetBooleanValue.ValueType = ...,
        defaultCanShare: global___SetBooleanValue.ValueType = ...,
        sharedFolderAddRecord: collections.abc.Iterable[global___SharedFolderUpdateRecord] | None = ...,
        sharedFolderAddUser: collections.abc.Iterable[global___SharedFolderUpdateUser] | None = ...,
        sharedFolderAddTeam: collections.abc.Iterable[global___SharedFolderUpdateTeam] | None = ...,
        sharedFolderUpdateRecord: collections.abc.Iterable[global___SharedFolderUpdateRecord] | None = ...,
        sharedFolderUpdateUser: collections.abc.Iterable[global___SharedFolderUpdateUser] | None = ...,
        sharedFolderUpdateTeam: collections.abc.Iterable[global___SharedFolderUpdateTeam] | None = ...,
        sharedFolderRemoveRecord: collections.abc.Iterable[builtins.bytes] | None = ...,
        sharedFolderRemoveUser: collections.abc.Iterable[builtins.str] | None = ...,
        sharedFolderRemoveTeam: collections.abc.Iterable[builtins.bytes] | None = ...,
        sharedFolderOwner: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["defaultCanEdit", b"defaultCanEdit", "defaultCanShare", b"defaultCanShare", "defaultManageRecords", b"defaultManageRecords", "defaultManageUsers", b"defaultManageUsers", "encryptedSharedFolderName", b"encryptedSharedFolderName", "forceUpdate", b"forceUpdate", "fromTeamUid", b"fromTeamUid", "revision", b"revision", "sharedFolderAddRecord", b"sharedFolderAddRecord", "sharedFolderAddTeam", b"sharedFolderAddTeam", "sharedFolderAddUser", b"sharedFolderAddUser", "sharedFolderOwner", b"sharedFolderOwner", "sharedFolderRemoveRecord", b"sharedFolderRemoveRecord", "sharedFolderRemoveTeam", b"sharedFolderRemoveTeam", "sharedFolderRemoveUser", b"sharedFolderRemoveUser", "sharedFolderUid", b"sharedFolderUid", "sharedFolderUpdateOperation_dont_use", b"sharedFolderUpdateOperation_dont_use", "sharedFolderUpdateRecord", b"sharedFolderUpdateRecord", "sharedFolderUpdateTeam", b"sharedFolderUpdateTeam", "sharedFolderUpdateUser", b"sharedFolderUpdateUser"]) -> None: ...

global___SharedFolderUpdateV3Request = SharedFolderUpdateV3Request

@typing.final
class SharedFolderUpdateV3RequestV2(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHAREDFOLDERSUPDATEV3_FIELD_NUMBER: builtins.int
    @property
    def sharedFoldersUpdateV3(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SharedFolderUpdateV3Request]: ...
    def __init__(
        self,
        *,
        sharedFoldersUpdateV3: collections.abc.Iterable[global___SharedFolderUpdateV3Request] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["sharedFoldersUpdateV3", b"sharedFoldersUpdateV3"]) -> None: ...

global___SharedFolderUpdateV3RequestV2 = SharedFolderUpdateV3RequestV2

@typing.final
class SharedFolderUpdateRecordStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORDUID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    recordUid: builtins.bytes
    status: builtins.str
    def __init__(
        self,
        *,
        recordUid: builtins.bytes = ...,
        status: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["recordUid", b"recordUid", "status", b"status"]) -> None: ...

global___SharedFolderUpdateRecordStatus = SharedFolderUpdateRecordStatus

@typing.final
class SharedFolderUpdateUserStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    username: builtins.str
    status: builtins.str
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        status: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status", "username", b"username"]) -> None: ...

global___SharedFolderUpdateUserStatus = SharedFolderUpdateUserStatus

@typing.final
class SharedFolderUpdateTeamStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TEAMUID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    teamUid: builtins.bytes
    status: builtins.str
    def __init__(
        self,
        *,
        teamUid: builtins.bytes = ...,
        status: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status", "teamUid", b"teamUid"]) -> None: ...

global___SharedFolderUpdateTeamStatus = SharedFolderUpdateTeamStatus

@typing.final
class SharedFolderUpdateV3Response(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REVISION_FIELD_NUMBER: builtins.int
    SHAREDFOLDERADDRECORDSTATUS_FIELD_NUMBER: builtins.int
    SHAREDFOLDERADDUSERSTATUS_FIELD_NUMBER: builtins.int
    SHAREDFOLDERADDTEAMSTATUS_FIELD_NUMBER: builtins.int
    SHAREDFOLDERUPDATERECORDSTATUS_FIELD_NUMBER: builtins.int
    SHAREDFOLDERUPDATEUSERSTATUS_FIELD_NUMBER: builtins.int
    SHAREDFOLDERUPDATETEAMSTATUS_FIELD_NUMBER: builtins.int
    SHAREDFOLDERREMOVERECORDSTATUS_FIELD_NUMBER: builtins.int
    SHAREDFOLDERREMOVEUSERSTATUS_FIELD_NUMBER: builtins.int
    SHAREDFOLDERREMOVETEAMSTATUS_FIELD_NUMBER: builtins.int
    SHAREDFOLDERUID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    revision: builtins.int
    sharedFolderUid: builtins.bytes
    status: builtins.str
    @property
    def sharedFolderAddRecordStatus(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SharedFolderUpdateRecordStatus]: ...
    @property
    def sharedFolderAddUserStatus(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SharedFolderUpdateUserStatus]: ...
    @property
    def sharedFolderAddTeamStatus(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SharedFolderUpdateTeamStatus]: ...
    @property
    def sharedFolderUpdateRecordStatus(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SharedFolderUpdateRecordStatus]: ...
    @property
    def sharedFolderUpdateUserStatus(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SharedFolderUpdateUserStatus]: ...
    @property
    def sharedFolderUpdateTeamStatus(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SharedFolderUpdateTeamStatus]: ...
    @property
    def sharedFolderRemoveRecordStatus(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SharedFolderUpdateRecordStatus]: ...
    @property
    def sharedFolderRemoveUserStatus(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SharedFolderUpdateUserStatus]: ...
    @property
    def sharedFolderRemoveTeamStatus(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SharedFolderUpdateTeamStatus]: ...
    def __init__(
        self,
        *,
        revision: builtins.int = ...,
        sharedFolderAddRecordStatus: collections.abc.Iterable[global___SharedFolderUpdateRecordStatus] | None = ...,
        sharedFolderAddUserStatus: collections.abc.Iterable[global___SharedFolderUpdateUserStatus] | None = ...,
        sharedFolderAddTeamStatus: collections.abc.Iterable[global___SharedFolderUpdateTeamStatus] | None = ...,
        sharedFolderUpdateRecordStatus: collections.abc.Iterable[global___SharedFolderUpdateRecordStatus] | None = ...,
        sharedFolderUpdateUserStatus: collections.abc.Iterable[global___SharedFolderUpdateUserStatus] | None = ...,
        sharedFolderUpdateTeamStatus: collections.abc.Iterable[global___SharedFolderUpdateTeamStatus] | None = ...,
        sharedFolderRemoveRecordStatus: collections.abc.Iterable[global___SharedFolderUpdateRecordStatus] | None = ...,
        sharedFolderRemoveUserStatus: collections.abc.Iterable[global___SharedFolderUpdateUserStatus] | None = ...,
        sharedFolderRemoveTeamStatus: collections.abc.Iterable[global___SharedFolderUpdateTeamStatus] | None = ...,
        sharedFolderUid: builtins.bytes = ...,
        status: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["revision", b"revision", "sharedFolderAddRecordStatus", b"sharedFolderAddRecordStatus", "sharedFolderAddTeamStatus", b"sharedFolderAddTeamStatus", "sharedFolderAddUserStatus", b"sharedFolderAddUserStatus", "sharedFolderRemoveRecordStatus", b"sharedFolderRemoveRecordStatus", "sharedFolderRemoveTeamStatus", b"sharedFolderRemoveTeamStatus", "sharedFolderRemoveUserStatus", b"sharedFolderRemoveUserStatus", "sharedFolderUid", b"sharedFolderUid", "sharedFolderUpdateRecordStatus", b"sharedFolderUpdateRecordStatus", "sharedFolderUpdateTeamStatus", b"sharedFolderUpdateTeamStatus", "sharedFolderUpdateUserStatus", b"sharedFolderUpdateUserStatus", "status", b"status"]) -> None: ...

global___SharedFolderUpdateV3Response = SharedFolderUpdateV3Response

@typing.final
class SharedFolderUpdateV3ResponseV2(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHAREDFOLDERSUPDATEV3RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def sharedFoldersUpdateV3Response(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SharedFolderUpdateV3Response]: ...
    def __init__(
        self,
        *,
        sharedFoldersUpdateV3Response: collections.abc.Iterable[global___SharedFolderUpdateV3Response] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["sharedFoldersUpdateV3Response", b"sharedFoldersUpdateV3Response"]) -> None: ...

global___SharedFolderUpdateV3ResponseV2 = SharedFolderUpdateV3ResponseV2

@typing.final
class GetDeletedSharedFoldersAndRecordsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHAREDFOLDERS_FIELD_NUMBER: builtins.int
    SHAREDFOLDERRECORDS_FIELD_NUMBER: builtins.int
    DELETEDRECORDDATA_FIELD_NUMBER: builtins.int
    USERNAMES_FIELD_NUMBER: builtins.int
    @property
    def sharedFolders(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DeletedSharedFolder]: ...
    @property
    def sharedFolderRecords(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DeletedSharedFolderRecord]: ...
    @property
    def deletedRecordData(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DeletedRecordData]: ...
    @property
    def usernames(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Username]: ...
    def __init__(
        self,
        *,
        sharedFolders: collections.abc.Iterable[global___DeletedSharedFolder] | None = ...,
        sharedFolderRecords: collections.abc.Iterable[global___DeletedSharedFolderRecord] | None = ...,
        deletedRecordData: collections.abc.Iterable[global___DeletedRecordData] | None = ...,
        usernames: collections.abc.Iterable[global___Username] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["deletedRecordData", b"deletedRecordData", "sharedFolderRecords", b"sharedFolderRecords", "sharedFolders", b"sharedFolders", "usernames", b"usernames"]) -> None: ...

global___GetDeletedSharedFoldersAndRecordsResponse = GetDeletedSharedFoldersAndRecordsResponse

@typing.final
class DeletedSharedFolder(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHAREDFOLDERUID_FIELD_NUMBER: builtins.int
    FOLDERUID_FIELD_NUMBER: builtins.int
    PARENTUID_FIELD_NUMBER: builtins.int
    SHAREDFOLDERKEY_FIELD_NUMBER: builtins.int
    FOLDERKEYTYPE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    DATEDELETED_FIELD_NUMBER: builtins.int
    REVISION_FIELD_NUMBER: builtins.int
    sharedFolderUid: builtins.bytes
    folderUid: builtins.bytes
    parentUid: builtins.bytes
    sharedFolderKey: builtins.bytes
    folderKeyType: record_pb2.RecordKeyType.ValueType
    data: builtins.bytes
    dateDeleted: builtins.int
    revision: builtins.int
    def __init__(
        self,
        *,
        sharedFolderUid: builtins.bytes = ...,
        folderUid: builtins.bytes = ...,
        parentUid: builtins.bytes = ...,
        sharedFolderKey: builtins.bytes = ...,
        folderKeyType: record_pb2.RecordKeyType.ValueType = ...,
        data: builtins.bytes = ...,
        dateDeleted: builtins.int = ...,
        revision: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "dateDeleted", b"dateDeleted", "folderKeyType", b"folderKeyType", "folderUid", b"folderUid", "parentUid", b"parentUid", "revision", b"revision", "sharedFolderKey", b"sharedFolderKey", "sharedFolderUid", b"sharedFolderUid"]) -> None: ...

global___DeletedSharedFolder = DeletedSharedFolder

@typing.final
class DeletedSharedFolderRecord(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOLDERUID_FIELD_NUMBER: builtins.int
    RECORDUID_FIELD_NUMBER: builtins.int
    SHAREDRECORDKEY_FIELD_NUMBER: builtins.int
    DATEDELETED_FIELD_NUMBER: builtins.int
    REVISION_FIELD_NUMBER: builtins.int
    folderUid: builtins.bytes
    recordUid: builtins.bytes
    sharedRecordKey: builtins.bytes
    dateDeleted: builtins.int
    revision: builtins.int
    def __init__(
        self,
        *,
        folderUid: builtins.bytes = ...,
        recordUid: builtins.bytes = ...,
        sharedRecordKey: builtins.bytes = ...,
        dateDeleted: builtins.int = ...,
        revision: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["dateDeleted", b"dateDeleted", "folderUid", b"folderUid", "recordUid", b"recordUid", "revision", b"revision", "sharedRecordKey", b"sharedRecordKey"]) -> None: ...

global___DeletedSharedFolderRecord = DeletedSharedFolderRecord

@typing.final
class DeletedRecordData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORDUID_FIELD_NUMBER: builtins.int
    OWNERUID_FIELD_NUMBER: builtins.int
    REVISION_FIELD_NUMBER: builtins.int
    CLIENTMODIFIEDTIME_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    recordUid: builtins.bytes
    ownerUid: builtins.bytes
    revision: builtins.int
    clientModifiedTime: builtins.int
    data: builtins.bytes
    version: builtins.int
    def __init__(
        self,
        *,
        recordUid: builtins.bytes = ...,
        ownerUid: builtins.bytes = ...,
        revision: builtins.int = ...,
        clientModifiedTime: builtins.int = ...,
        data: builtins.bytes = ...,
        version: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["clientModifiedTime", b"clientModifiedTime", "data", b"data", "ownerUid", b"ownerUid", "recordUid", b"recordUid", "revision", b"revision", "version", b"version"]) -> None: ...

global___DeletedRecordData = DeletedRecordData

@typing.final
class Username(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNTUID_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    accountUid: builtins.bytes
    username: builtins.str
    def __init__(
        self,
        *,
        accountUid: builtins.bytes = ...,
        username: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["accountUid", b"accountUid", "username", b"username"]) -> None: ...

global___Username = Username

@typing.final
class RestoreDeletedSharedFoldersAndRecordsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOLDERS_FIELD_NUMBER: builtins.int
    RECORDS_FIELD_NUMBER: builtins.int
    @property
    def folders(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RestoreSharedObject]: ...
    @property
    def records(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RestoreSharedObject]: ...
    def __init__(
        self,
        *,
        folders: collections.abc.Iterable[global___RestoreSharedObject] | None = ...,
        records: collections.abc.Iterable[global___RestoreSharedObject] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["folders", b"folders", "records", b"records"]) -> None: ...

global___RestoreDeletedSharedFoldersAndRecordsRequest = RestoreDeletedSharedFoldersAndRecordsRequest

@typing.final
class RestoreSharedObject(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOLDERUID_FIELD_NUMBER: builtins.int
    RECORDUIDS_FIELD_NUMBER: builtins.int
    folderUid: builtins.bytes
    @property
    def recordUids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        folderUid: builtins.bytes = ...,
        recordUids: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["folderUid", b"folderUid", "recordUids", b"recordUids"]) -> None: ...

global___RestoreSharedObject = RestoreSharedObject
