"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import enterprise_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import record_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _WebRtcConnectionType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _WebRtcConnectionTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WebRtcConnectionType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CONNECTION: _WebRtcConnectionType.ValueType  # 0
    TUNNEL: _WebRtcConnectionType.ValueType  # 1
    SSH: _WebRtcConnectionType.ValueType  # 2
    RDP: _WebRtcConnectionType.ValueType  # 3
    HTTP: _WebRtcConnectionType.ValueType  # 4
    VNC: _WebRtcConnectionType.ValueType  # 5
    TELNET: _WebRtcConnectionType.ValueType  # 6
    MYSQL: _WebRtcConnectionType.ValueType  # 7
    SQL_SERVER: _WebRtcConnectionType.ValueType  # 8
    POSTGRESQL: _WebRtcConnectionType.ValueType  # 9

class WebRtcConnectionType(_WebRtcConnectionType, metaclass=_WebRtcConnectionTypeEnumTypeWrapper): ...

CONNECTION: WebRtcConnectionType.ValueType  # 0
TUNNEL: WebRtcConnectionType.ValueType  # 1
SSH: WebRtcConnectionType.ValueType  # 2
RDP: WebRtcConnectionType.ValueType  # 3
HTTP: WebRtcConnectionType.ValueType  # 4
VNC: WebRtcConnectionType.ValueType  # 5
TELNET: WebRtcConnectionType.ValueType  # 6
MYSQL: WebRtcConnectionType.ValueType  # 7
SQL_SERVER: WebRtcConnectionType.ValueType  # 8
POSTGRESQL: WebRtcConnectionType.ValueType  # 9
global___WebRtcConnectionType = WebRtcConnectionType

class _PAMOperationType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PAMOperationTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PAMOperationType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ADD: _PAMOperationType.ValueType  # 0
    UPDATE: _PAMOperationType.ValueType  # 1
    REPLACE: _PAMOperationType.ValueType  # 2
    DELETE: _PAMOperationType.ValueType  # 3

class PAMOperationType(_PAMOperationType, metaclass=_PAMOperationTypeEnumTypeWrapper): ...

ADD: PAMOperationType.ValueType  # 0
UPDATE: PAMOperationType.ValueType  # 1
REPLACE: PAMOperationType.ValueType  # 2
DELETE: PAMOperationType.ValueType  # 3
global___PAMOperationType = PAMOperationType

class _PAMOperationResultType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PAMOperationResultTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PAMOperationResultType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    POT_SUCCESS: _PAMOperationResultType.ValueType  # 0
    POT_UNKNOWN_ERROR: _PAMOperationResultType.ValueType  # 1
    POT_ALREADY_EXISTS: _PAMOperationResultType.ValueType  # 2
    POT_DOES_NOT_EXIST: _PAMOperationResultType.ValueType  # 3

class PAMOperationResultType(_PAMOperationResultType, metaclass=_PAMOperationResultTypeEnumTypeWrapper): ...

POT_SUCCESS: PAMOperationResultType.ValueType  # 0
POT_UNKNOWN_ERROR: PAMOperationResultType.ValueType  # 1
POT_ALREADY_EXISTS: PAMOperationResultType.ValueType  # 2
POT_DOES_NOT_EXIST: PAMOperationResultType.ValueType  # 3
global___PAMOperationResultType = PAMOperationResultType

class _ControllerMessageType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ControllerMessageTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ControllerMessageType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CMT_GENERAL: _ControllerMessageType.ValueType  # 0
    CMT_ROTATE: _ControllerMessageType.ValueType  # 1
    CMT_DISCOVERY: _ControllerMessageType.ValueType  # 2
    CMT_CONNECT: _ControllerMessageType.ValueType  # 3
    """make a webrtc connection outside of router"""

class ControllerMessageType(_ControllerMessageType, metaclass=_ControllerMessageTypeEnumTypeWrapper): ...

CMT_GENERAL: ControllerMessageType.ValueType  # 0
CMT_ROTATE: ControllerMessageType.ValueType  # 1
CMT_DISCOVERY: ControllerMessageType.ValueType  # 2
CMT_CONNECT: ControllerMessageType.ValueType  # 3
"""make a webrtc connection outside of router"""
global___ControllerMessageType = ControllerMessageType

class _PAMRecordingType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PAMRecordingTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PAMRecordingType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PRT_SESSION: _PAMRecordingType.ValueType  # 0
    PRT_TYPESCRIPT: _PAMRecordingType.ValueType  # 1
    PRT_TIME: _PAMRecordingType.ValueType  # 2

class PAMRecordingType(_PAMRecordingType, metaclass=_PAMRecordingTypeEnumTypeWrapper): ...

PRT_SESSION: PAMRecordingType.ValueType  # 0
PRT_TYPESCRIPT: PAMRecordingType.ValueType  # 1
PRT_TIME: PAMRecordingType.ValueType  # 2
global___PAMRecordingType = PAMRecordingType

@typing.final
class PAMRotationSchedule(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORDUID_FIELD_NUMBER: builtins.int
    CONFIGURATIONUID_FIELD_NUMBER: builtins.int
    CONTROLLERUID_FIELD_NUMBER: builtins.int
    SCHEDULEDATA_FIELD_NUMBER: builtins.int
    NOSCHEDULE_FIELD_NUMBER: builtins.int
    recordUid: builtins.bytes
    configurationUid: builtins.bytes
    controllerUid: builtins.bytes
    scheduleData: builtins.str
    """comes from the scheduler, can be different from one in KA if out of sync"""
    noSchedule: builtins.bool
    """there is no schedule defined in KA"""
    def __init__(
        self,
        *,
        recordUid: builtins.bytes = ...,
        configurationUid: builtins.bytes = ...,
        controllerUid: builtins.bytes = ...,
        scheduleData: builtins.str = ...,
        noSchedule: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["configurationUid", b"configurationUid", "controllerUid", b"controllerUid", "noSchedule", b"noSchedule", "recordUid", b"recordUid", "scheduleData", b"scheduleData"]) -> None: ...

global___PAMRotationSchedule = PAMRotationSchedule

@typing.final
class PAMRotationSchedulesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCHEDULES_FIELD_NUMBER: builtins.int
    @property
    def schedules(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PAMRotationSchedule]: ...
    def __init__(
        self,
        *,
        schedules: collections.abc.Iterable[global___PAMRotationSchedule] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["schedules", b"schedules"]) -> None: ...

global___PAMRotationSchedulesResponse = PAMRotationSchedulesResponse

@typing.final
class PAMOnlineController(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTROLLERUID_FIELD_NUMBER: builtins.int
    CONNECTEDON_FIELD_NUMBER: builtins.int
    IPADDRESS_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    CONNECTIONS_FIELD_NUMBER: builtins.int
    controllerUid: builtins.bytes
    connectedOn: builtins.int
    ipAddress: builtins.str
    version: builtins.str
    @property
    def connections(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PAMWebRtcConnection]: ...
    def __init__(
        self,
        *,
        controllerUid: builtins.bytes = ...,
        connectedOn: builtins.int = ...,
        ipAddress: builtins.str = ...,
        version: builtins.str = ...,
        connections: collections.abc.Iterable[global___PAMWebRtcConnection] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["connectedOn", b"connectedOn", "connections", b"connections", "controllerUid", b"controllerUid", "ipAddress", b"ipAddress", "version", b"version"]) -> None: ...

global___PAMOnlineController = PAMOnlineController

@typing.final
class PAMWebRtcConnection(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONNECTIONUID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    RECORDUID_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    STARTEDON_FIELD_NUMBER: builtins.int
    CONFIGURATIONUID_FIELD_NUMBER: builtins.int
    connectionUid: builtins.bytes
    type: global___WebRtcConnectionType.ValueType
    recordUid: builtins.bytes
    userName: builtins.str
    startedOn: builtins.int
    configurationUid: builtins.bytes
    def __init__(
        self,
        *,
        connectionUid: builtins.bytes = ...,
        type: global___WebRtcConnectionType.ValueType = ...,
        recordUid: builtins.bytes = ...,
        userName: builtins.str = ...,
        startedOn: builtins.int = ...,
        configurationUid: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["configurationUid", b"configurationUid", "connectionUid", b"connectionUid", "recordUid", b"recordUid", "startedOn", b"startedOn", "type", b"type", "userName", b"userName"]) -> None: ...

global___PAMWebRtcConnection = PAMWebRtcConnection

@typing.final
class PAMOnlineControllers(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEPRECATED_FIELD_NUMBER: builtins.int
    CONTROLLERS_FIELD_NUMBER: builtins.int
    @property
    def deprecated(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    @property
    def controllers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PAMOnlineController]: ...
    def __init__(
        self,
        *,
        deprecated: collections.abc.Iterable[builtins.bytes] | None = ...,
        controllers: collections.abc.Iterable[global___PAMOnlineController] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["controllers", b"controllers", "deprecated", b"deprecated"]) -> None: ...

global___PAMOnlineControllers = PAMOnlineControllers

@typing.final
class PAMRotateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUESTUID_FIELD_NUMBER: builtins.int
    RECORDUID_FIELD_NUMBER: builtins.int
    requestUid: builtins.bytes
    recordUid: builtins.bytes
    def __init__(
        self,
        *,
        requestUid: builtins.bytes = ...,
        recordUid: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["recordUid", b"recordUid", "requestUid", b"requestUid"]) -> None: ...

global___PAMRotateRequest = PAMRotateRequest

@typing.final
class PAMControllersResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTROLLERS_FIELD_NUMBER: builtins.int
    @property
    def controllers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PAMController]: ...
    def __init__(
        self,
        *,
        controllers: collections.abc.Iterable[global___PAMController] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["controllers", b"controllers"]) -> None: ...

global___PAMControllersResponse = PAMControllersResponse

@typing.final
class PAMRemoveController(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTROLLERUID_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    controllerUid: builtins.bytes
    message: builtins.str
    def __init__(
        self,
        *,
        controllerUid: builtins.bytes = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["controllerUid", b"controllerUid", "message", b"message"]) -> None: ...

global___PAMRemoveController = PAMRemoveController

@typing.final
class PAMRemoveControllerResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTROLLERS_FIELD_NUMBER: builtins.int
    @property
    def controllers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PAMRemoveController]: ...
    def __init__(
        self,
        *,
        controllers: collections.abc.Iterable[global___PAMRemoveController] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["controllers", b"controllers"]) -> None: ...

global___PAMRemoveControllerResponse = PAMRemoveControllerResponse

@typing.final
class PAMModifyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPERATIONS_FIELD_NUMBER: builtins.int
    @property
    def operations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PAMDataOperation]: ...
    def __init__(
        self,
        *,
        operations: collections.abc.Iterable[global___PAMDataOperation] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["operations", b"operations"]) -> None: ...

global___PAMModifyRequest = PAMModifyRequest

@typing.final
class PAMDataOperation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPERATIONTYPE_FIELD_NUMBER: builtins.int
    CONFIGURATION_FIELD_NUMBER: builtins.int
    ELEMENT_FIELD_NUMBER: builtins.int
    operationType: global___PAMOperationType.ValueType
    @property
    def configuration(self) -> global___PAMConfigurationData: ...
    @property
    def element(self) -> global___PAMElementData: ...
    def __init__(
        self,
        *,
        operationType: global___PAMOperationType.ValueType = ...,
        configuration: global___PAMConfigurationData | None = ...,
        element: global___PAMElementData | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["configuration", b"configuration", "element", b"element"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["configuration", b"configuration", "element", b"element", "operationType", b"operationType"]) -> None: ...

global___PAMDataOperation = PAMDataOperation

@typing.final
class PAMConfigurationData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONFIGURATIONUID_FIELD_NUMBER: builtins.int
    NODEID_FIELD_NUMBER: builtins.int
    CONTROLLERUID_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    configurationUid: builtins.bytes
    nodeId: builtins.int
    controllerUid: builtins.bytes
    data: builtins.bytes
    def __init__(
        self,
        *,
        configurationUid: builtins.bytes = ...,
        nodeId: builtins.int = ...,
        controllerUid: builtins.bytes = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["configurationUid", b"configurationUid", "controllerUid", b"controllerUid", "data", b"data", "nodeId", b"nodeId"]) -> None: ...

global___PAMConfigurationData = PAMConfigurationData

@typing.final
class PAMElementData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ELEMENTUID_FIELD_NUMBER: builtins.int
    PARENTUID_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    elementUid: builtins.bytes
    parentUid: builtins.bytes
    data: builtins.bytes
    def __init__(
        self,
        *,
        elementUid: builtins.bytes = ...,
        parentUid: builtins.bytes = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "elementUid", b"elementUid", "parentUid", b"parentUid"]) -> None: ...

global___PAMElementData = PAMElementData

@typing.final
class PAMElementOperationResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ELEMENTUID_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    elementUid: builtins.bytes
    result: global___PAMOperationResultType.ValueType
    message: builtins.str
    def __init__(
        self,
        *,
        elementUid: builtins.bytes = ...,
        result: global___PAMOperationResultType.ValueType = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["elementUid", b"elementUid", "message", b"message", "result", b"result"]) -> None: ...

global___PAMElementOperationResult = PAMElementOperationResult

@typing.final
class PAMModifyResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESULTS_FIELD_NUMBER: builtins.int
    @property
    def results(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PAMElementOperationResult]: ...
    def __init__(
        self,
        *,
        results: collections.abc.Iterable[global___PAMElementOperationResult] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["results", b"results"]) -> None: ...

global___PAMModifyResult = PAMModifyResult

@typing.final
class PAMElement(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ELEMENTUID_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    CREATED_FIELD_NUMBER: builtins.int
    LASTMODIFIED_FIELD_NUMBER: builtins.int
    CHILDREN_FIELD_NUMBER: builtins.int
    elementUid: builtins.bytes
    data: builtins.bytes
    created: builtins.int
    lastModified: builtins.int
    @property
    def children(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PAMElement]: ...
    def __init__(
        self,
        *,
        elementUid: builtins.bytes = ...,
        data: builtins.bytes = ...,
        created: builtins.int = ...,
        lastModified: builtins.int = ...,
        children: collections.abc.Iterable[global___PAMElement] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["children", b"children", "created", b"created", "data", b"data", "elementUid", b"elementUid", "lastModified", b"lastModified"]) -> None: ...

global___PAMElement = PAMElement

@typing.final
class PAMGenericUidRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UID_FIELD_NUMBER: builtins.int
    uid: builtins.bytes
    def __init__(
        self,
        *,
        uid: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["uid", b"uid"]) -> None: ...

global___PAMGenericUidRequest = PAMGenericUidRequest

@typing.final
class PAMGenericUidsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UIDS_FIELD_NUMBER: builtins.int
    @property
    def uids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        uids: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["uids", b"uids"]) -> None: ...

global___PAMGenericUidsRequest = PAMGenericUidsRequest

@typing.final
class PAMConfiguration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONFIGURATIONUID_FIELD_NUMBER: builtins.int
    NODEID_FIELD_NUMBER: builtins.int
    CONTROLLERUID_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    CREATED_FIELD_NUMBER: builtins.int
    LASTMODIFIED_FIELD_NUMBER: builtins.int
    CHILDREN_FIELD_NUMBER: builtins.int
    configurationUid: builtins.bytes
    nodeId: builtins.int
    controllerUid: builtins.bytes
    data: builtins.bytes
    created: builtins.int
    lastModified: builtins.int
    @property
    def children(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PAMElement]: ...
    def __init__(
        self,
        *,
        configurationUid: builtins.bytes = ...,
        nodeId: builtins.int = ...,
        controllerUid: builtins.bytes = ...,
        data: builtins.bytes = ...,
        created: builtins.int = ...,
        lastModified: builtins.int = ...,
        children: collections.abc.Iterable[global___PAMElement] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["children", b"children", "configurationUid", b"configurationUid", "controllerUid", b"controllerUid", "created", b"created", "data", b"data", "lastModified", b"lastModified", "nodeId", b"nodeId"]) -> None: ...

global___PAMConfiguration = PAMConfiguration

@typing.final
class PAMConfigurations(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONFIGURATIONS_FIELD_NUMBER: builtins.int
    @property
    def configurations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PAMConfiguration]: ...
    def __init__(
        self,
        *,
        configurations: collections.abc.Iterable[global___PAMConfiguration] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["configurations", b"configurations"]) -> None: ...

global___PAMConfigurations = PAMConfigurations

@typing.final
class PAMController(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTROLLERUID_FIELD_NUMBER: builtins.int
    CONTROLLERNAME_FIELD_NUMBER: builtins.int
    DEVICETOKEN_FIELD_NUMBER: builtins.int
    DEVICENAME_FIELD_NUMBER: builtins.int
    NODEID_FIELD_NUMBER: builtins.int
    CREATED_FIELD_NUMBER: builtins.int
    LASTMODIFIED_FIELD_NUMBER: builtins.int
    APPLICATIONUID_FIELD_NUMBER: builtins.int
    APPCLIENTTYPE_FIELD_NUMBER: builtins.int
    ISINITIALIZED_FIELD_NUMBER: builtins.int
    controllerUid: builtins.bytes
    controllerName: builtins.str
    deviceToken: builtins.str
    deviceName: builtins.str
    nodeId: builtins.int
    created: builtins.int
    lastModified: builtins.int
    applicationUid: builtins.bytes
    appClientType: enterprise_pb2.AppClientType.ValueType
    isInitialized: builtins.bool
    def __init__(
        self,
        *,
        controllerUid: builtins.bytes = ...,
        controllerName: builtins.str = ...,
        deviceToken: builtins.str = ...,
        deviceName: builtins.str = ...,
        nodeId: builtins.int = ...,
        created: builtins.int = ...,
        lastModified: builtins.int = ...,
        applicationUid: builtins.bytes = ...,
        appClientType: enterprise_pb2.AppClientType.ValueType = ...,
        isInitialized: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["appClientType", b"appClientType", "applicationUid", b"applicationUid", "controllerName", b"controllerName", "controllerUid", b"controllerUid", "created", b"created", "deviceName", b"deviceName", "deviceToken", b"deviceToken", "isInitialized", b"isInitialized", "lastModified", b"lastModified", "nodeId", b"nodeId"]) -> None: ...

global___PAMController = PAMController

@typing.final
class ControllerResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAYLOAD_FIELD_NUMBER: builtins.int
    payload: builtins.str
    def __init__(
        self,
        *,
        payload: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["payload", b"payload"]) -> None: ...

global___ControllerResponse = ControllerResponse

@typing.final
class PAMConfigurationController(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONFIGURATIONUID_FIELD_NUMBER: builtins.int
    CONTROLLERUID_FIELD_NUMBER: builtins.int
    configurationUid: builtins.bytes
    controllerUid: builtins.bytes
    def __init__(
        self,
        *,
        configurationUid: builtins.bytes = ...,
        controllerUid: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["configurationUid", b"configurationUid", "controllerUid", b"controllerUid"]) -> None: ...

global___PAMConfigurationController = PAMConfigurationController

@typing.final
class ConfigurationAddRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONFIGURATIONUID_FIELD_NUMBER: builtins.int
    RECORDKEY_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    RECORDLINKS_FIELD_NUMBER: builtins.int
    AUDIT_FIELD_NUMBER: builtins.int
    configurationUid: builtins.bytes
    recordKey: builtins.bytes
    data: builtins.bytes
    @property
    def recordLinks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[record_pb2.RecordLink]: ...
    @property
    def audit(self) -> record_pb2.RecordAudit: ...
    def __init__(
        self,
        *,
        configurationUid: builtins.bytes = ...,
        recordKey: builtins.bytes = ...,
        data: builtins.bytes = ...,
        recordLinks: collections.abc.Iterable[record_pb2.RecordLink] | None = ...,
        audit: record_pb2.RecordAudit | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["audit", b"audit"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["audit", b"audit", "configurationUid", b"configurationUid", "data", b"data", "recordKey", b"recordKey", "recordLinks", b"recordLinks"]) -> None: ...

global___ConfigurationAddRequest = ConfigurationAddRequest

@typing.final
class RelayAccessCreds(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    SERVERTIME_FIELD_NUMBER: builtins.int
    username: builtins.str
    password: builtins.str
    serverTime: builtins.int
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        password: builtins.str = ...,
        serverTime: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["password", b"password", "serverTime", b"serverTime", "username", b"username"]) -> None: ...

global___RelayAccessCreds = RelayAccessCreds

@typing.final
class PAMRecording(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONNECTIONUID_FIELD_NUMBER: builtins.int
    RECORDINGTYPE_FIELD_NUMBER: builtins.int
    RECORDUID_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    STARTEDON_FIELD_NUMBER: builtins.int
    LENGTH_FIELD_NUMBER: builtins.int
    FILESIZE_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    connectionUid: builtins.bytes
    recordingType: global___PAMRecordingType.ValueType
    recordUid: builtins.bytes
    userName: builtins.str
    startedOn: builtins.int
    length: builtins.int
    """seconds"""
    fileSize: builtins.int
    protocol: builtins.str
    def __init__(
        self,
        *,
        connectionUid: builtins.bytes = ...,
        recordingType: global___PAMRecordingType.ValueType = ...,
        recordUid: builtins.bytes = ...,
        userName: builtins.str = ...,
        startedOn: builtins.int = ...,
        length: builtins.int = ...,
        fileSize: builtins.int = ...,
        protocol: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["connectionUid", b"connectionUid", "fileSize", b"fileSize", "length", b"length", "protocol", b"protocol", "recordUid", b"recordUid", "recordingType", b"recordingType", "startedOn", b"startedOn", "userName", b"userName"]) -> None: ...

global___PAMRecording = PAMRecording

@typing.final
class PAMRecordingsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORDINGS_FIELD_NUMBER: builtins.int
    @property
    def recordings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PAMRecording]: ...
    def __init__(
        self,
        *,
        recordings: collections.abc.Iterable[global___PAMRecording] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["recordings", b"recordings"]) -> None: ...

global___PAMRecordingsResponse = PAMRecordingsResponse

@typing.final
class PAMData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERTEX_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    vertex: builtins.bytes
    content: builtins.bytes
    def __init__(
        self,
        *,
        vertex: builtins.bytes = ...,
        content: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["content", b"content", "vertex", b"vertex"]) -> None: ...

global___PAMData = PAMData

@typing.final
class UidList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UIDS_FIELD_NUMBER: builtins.int
    @property
    def uids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        uids: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["uids", b"uids"]) -> None: ...

global___UidList = UidList

@typing.final
class PAMResourceConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORDUID_FIELD_NUMBER: builtins.int
    NETWORKUID_FIELD_NUMBER: builtins.int
    ADMINUID_FIELD_NUMBER: builtins.int
    META_FIELD_NUMBER: builtins.int
    CONNECTIONSETTINGS_FIELD_NUMBER: builtins.int
    CONNECTUSERS_FIELD_NUMBER: builtins.int
    DOMAINUID_FIELD_NUMBER: builtins.int
    JITSETTINGS_FIELD_NUMBER: builtins.int
    recordUid: builtins.bytes
    """resource record uid"""
    networkUid: builtins.bytes
    adminUid: builtins.bytes
    meta: builtins.bytes
    connectionSettings: builtins.bytes
    domainUid: builtins.bytes
    jitSettings: builtins.bytes
    @property
    def connectUsers(self) -> global___UidList: ...
    def __init__(
        self,
        *,
        recordUid: builtins.bytes = ...,
        networkUid: builtins.bytes | None = ...,
        adminUid: builtins.bytes | None = ...,
        meta: builtins.bytes | None = ...,
        connectionSettings: builtins.bytes | None = ...,
        connectUsers: global___UidList | None = ...,
        domainUid: builtins.bytes | None = ...,
        jitSettings: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_adminUid", b"_adminUid", "_connectUsers", b"_connectUsers", "_connectionSettings", b"_connectionSettings", "_domainUid", b"_domainUid", "_jitSettings", b"_jitSettings", "_meta", b"_meta", "_networkUid", b"_networkUid", "adminUid", b"adminUid", "connectUsers", b"connectUsers", "connectionSettings", b"connectionSettings", "domainUid", b"domainUid", "jitSettings", b"jitSettings", "meta", b"meta", "networkUid", b"networkUid"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_adminUid", b"_adminUid", "_connectUsers", b"_connectUsers", "_connectionSettings", b"_connectionSettings", "_domainUid", b"_domainUid", "_jitSettings", b"_jitSettings", "_meta", b"_meta", "_networkUid", b"_networkUid", "adminUid", b"adminUid", "connectUsers", b"connectUsers", "connectionSettings", b"connectionSettings", "domainUid", b"domainUid", "jitSettings", b"jitSettings", "meta", b"meta", "networkUid", b"networkUid", "recordUid", b"recordUid"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_adminUid", b"_adminUid"]) -> typing.Literal["adminUid"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_connectUsers", b"_connectUsers"]) -> typing.Literal["connectUsers"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_connectionSettings", b"_connectionSettings"]) -> typing.Literal["connectionSettings"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_domainUid", b"_domainUid"]) -> typing.Literal["domainUid"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_jitSettings", b"_jitSettings"]) -> typing.Literal["jitSettings"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_meta", b"_meta"]) -> typing.Literal["meta"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_networkUid", b"_networkUid"]) -> typing.Literal["networkUid"] | None: ...

global___PAMResourceConfig = PAMResourceConfig
