"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import NotificationCenter_pb2
import builtins
import collections.abc
import folder_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _CollectionLinkType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CollectionLinkTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CollectionLinkType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CLT_OTHER: _CollectionLinkType.ValueType  # 0
    CLT_AGENT: _CollectionLinkType.ValueType  # 1
    CLT_POLICY: _CollectionLinkType.ValueType  # 2
    CLT_COLLECTION: _CollectionLinkType.ValueType  # 3
    CLT_DEPLOYMENT: _CollectionLinkType.ValueType  # 4

class CollectionLinkType(_CollectionLinkType, metaclass=_CollectionLinkTypeEnumTypeWrapper): ...

CLT_OTHER: CollectionLinkType.ValueType  # 0
CLT_AGENT: CollectionLinkType.ValueType  # 1
CLT_POLICY: CollectionLinkType.ValueType  # 2
CLT_COLLECTION: CollectionLinkType.ValueType  # 3
CLT_DEPLOYMENT: CollectionLinkType.ValueType  # 4
global___CollectionLinkType = CollectionLinkType

@typing.final
class PEDMTOTPValidateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    ENTERPRISEID_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    username: builtins.str
    enterpriseId: builtins.int
    code: builtins.int
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        enterpriseId: builtins.int = ...,
        code: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["code", b"code", "enterpriseId", b"enterpriseId", "username", b"username"]) -> None: ...

global___PEDMTOTPValidateRequest = PEDMTOTPValidateRequest

@typing.final
class PedmStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    @property
    def key(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        key: collections.abc.Iterable[builtins.bytes] | None = ...,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["key", b"key", "message", b"message", "success", b"success"]) -> None: ...

global___PedmStatus = PedmStatus

@typing.final
class PedmStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDSTATUS_FIELD_NUMBER: builtins.int
    UPDATESTATUS_FIELD_NUMBER: builtins.int
    REMOVESTATUS_FIELD_NUMBER: builtins.int
    @property
    def addStatus(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PedmStatus]: ...
    @property
    def updateStatus(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PedmStatus]: ...
    @property
    def removeStatus(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PedmStatus]: ...
    def __init__(
        self,
        *,
        addStatus: collections.abc.Iterable[global___PedmStatus] | None = ...,
        updateStatus: collections.abc.Iterable[global___PedmStatus] | None = ...,
        removeStatus: collections.abc.Iterable[global___PedmStatus] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["addStatus", b"addStatus", "removeStatus", b"removeStatus", "updateStatus", b"updateStatus"]) -> None: ...

global___PedmStatusResponse = PedmStatusResponse

@typing.final
class DeploymentData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    ECPRIVATEKEY_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Deployment name"""
    ecPrivateKey: builtins.bytes
    """Deployment private key"""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        ecPrivateKey: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ecPrivateKey", b"ecPrivateKey", "name", b"name"]) -> None: ...

global___DeploymentData = DeploymentData

@typing.final
class DeploymentCreateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEPLOYMENTUID_FIELD_NUMBER: builtins.int
    AESKEY_FIELD_NUMBER: builtins.int
    ECPUBLICKEY_FIELD_NUMBER: builtins.int
    SPIFFECERTIFICATE_FIELD_NUMBER: builtins.int
    ENCRYPTEDDATA_FIELD_NUMBER: builtins.int
    AGENTDATA_FIELD_NUMBER: builtins.int
    deploymentUid: builtins.bytes
    aesKey: builtins.bytes
    """Deployment AES key encrypted by enterprise tree key"""
    ecPublicKey: builtins.bytes
    """Deployment EC public key"""
    spiffeCertificate: builtins.bytes
    """X509 spiffe server root certificate"""
    encryptedData: builtins.bytes
    """DeploymentData encrypted by aesKey"""
    agentData: builtins.bytes
    """Agent data given to agent upon registration. JSON encrypted by deployment public key"""
    def __init__(
        self,
        *,
        deploymentUid: builtins.bytes = ...,
        aesKey: builtins.bytes = ...,
        ecPublicKey: builtins.bytes = ...,
        spiffeCertificate: builtins.bytes = ...,
        encryptedData: builtins.bytes = ...,
        agentData: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["aesKey", b"aesKey", "agentData", b"agentData", "deploymentUid", b"deploymentUid", "ecPublicKey", b"ecPublicKey", "encryptedData", b"encryptedData", "spiffeCertificate", b"spiffeCertificate"]) -> None: ...

global___DeploymentCreateRequest = DeploymentCreateRequest

@typing.final
class DeploymentUpdateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEPLOYMENTUID_FIELD_NUMBER: builtins.int
    ENCRYPTEDDATA_FIELD_NUMBER: builtins.int
    DISABLED_FIELD_NUMBER: builtins.int
    SPIFFECERTIFICATE_FIELD_NUMBER: builtins.int
    deploymentUid: builtins.bytes
    encryptedData: builtins.bytes
    """DeploymentData encrypted by aesKey"""
    disabled: folder_pb2.SetBooleanValue.ValueType
    """enable/disable deployment"""
    spiffeCertificate: builtins.bytes
    """X509 spiffe server root certificate"""
    def __init__(
        self,
        *,
        deploymentUid: builtins.bytes = ...,
        encryptedData: builtins.bytes = ...,
        disabled: folder_pb2.SetBooleanValue.ValueType = ...,
        spiffeCertificate: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["deploymentUid", b"deploymentUid", "disabled", b"disabled", "encryptedData", b"encryptedData", "spiffeCertificate", b"spiffeCertificate"]) -> None: ...

global___DeploymentUpdateRequest = DeploymentUpdateRequest

@typing.final
class ModifyDeploymentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDDEPLOYMENT_FIELD_NUMBER: builtins.int
    UPDATEDEPLOYMENT_FIELD_NUMBER: builtins.int
    REMOVEDEPLOYMENT_FIELD_NUMBER: builtins.int
    @property
    def addDeployment(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DeploymentCreateRequest]: ...
    @property
    def updateDeployment(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DeploymentUpdateRequest]: ...
    @property
    def removeDeployment(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        addDeployment: collections.abc.Iterable[global___DeploymentCreateRequest] | None = ...,
        updateDeployment: collections.abc.Iterable[global___DeploymentUpdateRequest] | None = ...,
        removeDeployment: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["addDeployment", b"addDeployment", "removeDeployment", b"removeDeployment", "updateDeployment", b"updateDeployment"]) -> None: ...

global___ModifyDeploymentRequest = ModifyDeploymentRequest

@typing.final
class AgentUpdate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AGENTUID_FIELD_NUMBER: builtins.int
    DISABLED_FIELD_NUMBER: builtins.int
    DEPLOYMENTUID_FIELD_NUMBER: builtins.int
    agentUid: builtins.bytes
    disabled: folder_pb2.SetBooleanValue.ValueType
    """enable/disable agent"""
    deploymentUid: builtins.bytes
    """Agent new deployment"""
    def __init__(
        self,
        *,
        agentUid: builtins.bytes = ...,
        disabled: folder_pb2.SetBooleanValue.ValueType = ...,
        deploymentUid: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["agentUid", b"agentUid", "deploymentUid", b"deploymentUid", "disabled", b"disabled"]) -> None: ...

global___AgentUpdate = AgentUpdate

@typing.final
class ModifyAgentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UPDATEAGENT_FIELD_NUMBER: builtins.int
    REMOVEAGENT_FIELD_NUMBER: builtins.int
    @property
    def updateAgent(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AgentUpdate]: ...
    @property
    def removeAgent(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        updateAgent: collections.abc.Iterable[global___AgentUpdate] | None = ...,
        removeAgent: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["removeAgent", b"removeAgent", "updateAgent", b"updateAgent"]) -> None: ...

global___ModifyAgentRequest = ModifyAgentRequest

@typing.final
class PolicyAdd(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POLICYUID_FIELD_NUMBER: builtins.int
    PLAINDATA_FIELD_NUMBER: builtins.int
    ENCRYPTEDDATA_FIELD_NUMBER: builtins.int
    ENCRYPTEDKEY_FIELD_NUMBER: builtins.int
    policyUid: builtins.bytes
    plainData: builtins.bytes
    """policy template"""
    encryptedData: builtins.bytes
    """policy data encrypted with the policy key"""
    encryptedKey: builtins.bytes
    """policy key encrypted with the hash agent key"""
    def __init__(
        self,
        *,
        policyUid: builtins.bytes = ...,
        plainData: builtins.bytes = ...,
        encryptedData: builtins.bytes = ...,
        encryptedKey: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["encryptedData", b"encryptedData", "encryptedKey", b"encryptedKey", "plainData", b"plainData", "policyUid", b"policyUid"]) -> None: ...

global___PolicyAdd = PolicyAdd

@typing.final
class PolicyUpdate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POLICYUID_FIELD_NUMBER: builtins.int
    PLAINDATA_FIELD_NUMBER: builtins.int
    ENCRYPTEDDATA_FIELD_NUMBER: builtins.int
    policyUid: builtins.bytes
    plainData: builtins.bytes
    """policy template"""
    encryptedData: builtins.bytes
    """policy data encrypted with the policy key"""
    def __init__(
        self,
        *,
        policyUid: builtins.bytes = ...,
        plainData: builtins.bytes = ...,
        encryptedData: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["encryptedData", b"encryptedData", "plainData", b"plainData", "policyUid", b"policyUid"]) -> None: ...

global___PolicyUpdate = PolicyUpdate

@typing.final
class PolicyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDPOLICY_FIELD_NUMBER: builtins.int
    UPDATEPOLICY_FIELD_NUMBER: builtins.int
    REMOVEPOLICY_FIELD_NUMBER: builtins.int
    @property
    def addPolicy(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PolicyAdd]: ...
    @property
    def updatePolicy(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PolicyUpdate]: ...
    @property
    def removePolicy(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        addPolicy: collections.abc.Iterable[global___PolicyAdd] | None = ...,
        updatePolicy: collections.abc.Iterable[global___PolicyUpdate] | None = ...,
        removePolicy: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["addPolicy", b"addPolicy", "removePolicy", b"removePolicy", "updatePolicy", b"updatePolicy"]) -> None: ...

global___PolicyRequest = PolicyRequest

@typing.final
class PolicyLink(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POLICYUID_FIELD_NUMBER: builtins.int
    COLLECTIONUID_FIELD_NUMBER: builtins.int
    policyUid: builtins.bytes
    @property
    def collectionUid(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        policyUid: builtins.bytes = ...,
        collectionUid: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["collectionUid", b"collectionUid", "policyUid", b"policyUid"]) -> None: ...

global___PolicyLink = PolicyLink

@typing.final
class SetPolicyCollectionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SETCOLLECTION_FIELD_NUMBER: builtins.int
    @property
    def setCollection(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PolicyLink]: ...
    def __init__(
        self,
        *,
        setCollection: collections.abc.Iterable[global___PolicyLink] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["setCollection", b"setCollection"]) -> None: ...

global___SetPolicyCollectionRequest = SetPolicyCollectionRequest

@typing.final
class SetPolicyCollectionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SETCOLLECTIONSTATUS_FIELD_NUMBER: builtins.int
    @property
    def setCollectionStatus(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PedmStatus]: ...
    def __init__(
        self,
        *,
        setCollectionStatus: collections.abc.Iterable[global___PedmStatus] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["setCollectionStatus", b"setCollectionStatus"]) -> None: ...

global___SetPolicyCollectionResponse = SetPolicyCollectionResponse

@typing.final
class CollectionValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COLLECTIONUID_FIELD_NUMBER: builtins.int
    COLLECTIONTYPE_FIELD_NUMBER: builtins.int
    ENCRYPTEDDATA_FIELD_NUMBER: builtins.int
    collectionUid: builtins.bytes
    collectionType: builtins.int
    """see documentation"""
    encryptedData: builtins.bytes
    """Collection data encrypted with the hash key"""
    def __init__(
        self,
        *,
        collectionUid: builtins.bytes = ...,
        collectionType: builtins.int = ...,
        encryptedData: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["collectionType", b"collectionType", "collectionUid", b"collectionUid", "encryptedData", b"encryptedData"]) -> None: ...

global___CollectionValue = CollectionValue

@typing.final
class CollectionLinkData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COLLECTIONUID_FIELD_NUMBER: builtins.int
    LINKUID_FIELD_NUMBER: builtins.int
    LINKTYPE_FIELD_NUMBER: builtins.int
    LINKDATA_FIELD_NUMBER: builtins.int
    collectionUid: builtins.bytes
    linkUid: builtins.bytes
    linkType: global___CollectionLinkType.ValueType
    linkData: builtins.bytes
    """"File" collection UID"""
    def __init__(
        self,
        *,
        collectionUid: builtins.bytes = ...,
        linkUid: builtins.bytes = ...,
        linkType: global___CollectionLinkType.ValueType = ...,
        linkData: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["collectionUid", b"collectionUid", "linkData", b"linkData", "linkType", b"linkType", "linkUid", b"linkUid"]) -> None: ...

global___CollectionLinkData = CollectionLinkData

@typing.final
class CollectionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDCOLLECTION_FIELD_NUMBER: builtins.int
    UPDATECOLLECTION_FIELD_NUMBER: builtins.int
    REMOVECOLLECTION_FIELD_NUMBER: builtins.int
    @property
    def addCollection(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CollectionValue]: ...
    @property
    def updateCollection(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CollectionValue]: ...
    @property
    def removeCollection(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        addCollection: collections.abc.Iterable[global___CollectionValue] | None = ...,
        updateCollection: collections.abc.Iterable[global___CollectionValue] | None = ...,
        removeCollection: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["addCollection", b"addCollection", "removeCollection", b"removeCollection", "updateCollection", b"updateCollection"]) -> None: ...

global___CollectionRequest = CollectionRequest

@typing.final
class SetCollectionLinkRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDCOLLECTION_FIELD_NUMBER: builtins.int
    REMOVECOLLECTION_FIELD_NUMBER: builtins.int
    @property
    def addCollection(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CollectionLinkData]: ...
    @property
    def removeCollection(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CollectionLink]: ...
    def __init__(
        self,
        *,
        addCollection: collections.abc.Iterable[global___CollectionLinkData] | None = ...,
        removeCollection: collections.abc.Iterable[global___CollectionLink] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["addCollection", b"addCollection", "removeCollection", b"removeCollection"]) -> None: ...

global___SetCollectionLinkRequest = SetCollectionLinkRequest

@typing.final
class ApprovalActionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    APPROVE_FIELD_NUMBER: builtins.int
    DENY_FIELD_NUMBER: builtins.int
    REMOVE_FIELD_NUMBER: builtins.int
    @property
    def approve(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    @property
    def deny(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    @property
    def remove(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        approve: collections.abc.Iterable[builtins.bytes] | None = ...,
        deny: collections.abc.Iterable[builtins.bytes] | None = ...,
        remove: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["approve", b"approve", "deny", b"deny", "remove", b"remove"]) -> None: ...

global___ApprovalActionRequest = ApprovalActionRequest

@typing.final
class ApprovalActionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    APPROVE_FIELD_NUMBER: builtins.int
    DENY_FIELD_NUMBER: builtins.int
    REMOVE_FIELD_NUMBER: builtins.int
    @property
    def approve(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PedmStatus]: ...
    @property
    def deny(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PedmStatus]: ...
    @property
    def remove(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PedmStatus]: ...
    def __init__(
        self,
        *,
        approve: collections.abc.Iterable[global___PedmStatus] | None = ...,
        deny: collections.abc.Iterable[global___PedmStatus] | None = ...,
        remove: collections.abc.Iterable[global___PedmStatus] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["approve", b"approve", "deny", b"deny", "remove", b"remove"]) -> None: ...

global___ApprovalActionResponse = ApprovalActionResponse

@typing.final
class DeploymentNode(google.protobuf.message.Message):
    """PEDM Sync Down"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEPLOYMENTUID_FIELD_NUMBER: builtins.int
    DISABLED_FIELD_NUMBER: builtins.int
    AESKEY_FIELD_NUMBER: builtins.int
    ECPUBLICKEY_FIELD_NUMBER: builtins.int
    ENCRYPTEDDATA_FIELD_NUMBER: builtins.int
    AGENTDATA_FIELD_NUMBER: builtins.int
    CREATED_FIELD_NUMBER: builtins.int
    MODIFIED_FIELD_NUMBER: builtins.int
    deploymentUid: builtins.bytes
    disabled: builtins.bool
    """is deployment disabled"""
    aesKey: builtins.bytes
    """deployment key encrypted with the enterprise tree key"""
    ecPublicKey: builtins.bytes
    """deployment EC public Key"""
    encryptedData: builtins.bytes
    """DeploymentData encrypted with the deployment AES key"""
    agentData: builtins.bytes
    """Agent data given to agent upon registration. JSON encrypted by deployment public key"""
    created: builtins.int
    modified: builtins.int
    def __init__(
        self,
        *,
        deploymentUid: builtins.bytes = ...,
        disabled: builtins.bool = ...,
        aesKey: builtins.bytes = ...,
        ecPublicKey: builtins.bytes = ...,
        encryptedData: builtins.bytes = ...,
        agentData: builtins.bytes = ...,
        created: builtins.int = ...,
        modified: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["aesKey", b"aesKey", "agentData", b"agentData", "created", b"created", "deploymentUid", b"deploymentUid", "disabled", b"disabled", "ecPublicKey", b"ecPublicKey", "encryptedData", b"encryptedData", "modified", b"modified"]) -> None: ...

global___DeploymentNode = DeploymentNode

@typing.final
class AgentNode(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AGENTUID_FIELD_NUMBER: builtins.int
    MACHINEID_FIELD_NUMBER: builtins.int
    DEPLOYMENTUID_FIELD_NUMBER: builtins.int
    ECPUBLICKEY_FIELD_NUMBER: builtins.int
    DISABLED_FIELD_NUMBER: builtins.int
    ENCRYPTEDDATA_FIELD_NUMBER: builtins.int
    CREATED_FIELD_NUMBER: builtins.int
    MODIFIED_FIELD_NUMBER: builtins.int
    agentUid: builtins.bytes
    machineId: builtins.str
    """unique machine identifier"""
    deploymentUid: builtins.bytes
    ecPublicKey: builtins.bytes
    """Agent EC public key"""
    disabled: builtins.bool
    """is agent disabled"""
    encryptedData: builtins.bytes
    """Agent info encrypted with the hash key"""
    created: builtins.int
    modified: builtins.int
    def __init__(
        self,
        *,
        agentUid: builtins.bytes = ...,
        machineId: builtins.str = ...,
        deploymentUid: builtins.bytes = ...,
        ecPublicKey: builtins.bytes = ...,
        disabled: builtins.bool = ...,
        encryptedData: builtins.bytes = ...,
        created: builtins.int = ...,
        modified: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["agentUid", b"agentUid", "created", b"created", "deploymentUid", b"deploymentUid", "disabled", b"disabled", "ecPublicKey", b"ecPublicKey", "encryptedData", b"encryptedData", "machineId", b"machineId", "modified", b"modified"]) -> None: ...

global___AgentNode = AgentNode

@typing.final
class PolicyNode(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POLICYUID_FIELD_NUMBER: builtins.int
    PLAINDATA_FIELD_NUMBER: builtins.int
    ENCRYPTEDDATA_FIELD_NUMBER: builtins.int
    ENCRYPTEDKEY_FIELD_NUMBER: builtins.int
    CREATED_FIELD_NUMBER: builtins.int
    MODIFIED_FIELD_NUMBER: builtins.int
    policyUid: builtins.bytes
    plainData: builtins.bytes
    """policy template"""
    encryptedData: builtins.bytes
    """policy data encrypted with the policy key"""
    encryptedKey: builtins.bytes
    """policy key encrypted with the hash key"""
    created: builtins.int
    modified: builtins.int
    def __init__(
        self,
        *,
        policyUid: builtins.bytes = ...,
        plainData: builtins.bytes = ...,
        encryptedData: builtins.bytes = ...,
        encryptedKey: builtins.bytes = ...,
        created: builtins.int = ...,
        modified: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["created", b"created", "encryptedData", b"encryptedData", "encryptedKey", b"encryptedKey", "modified", b"modified", "plainData", b"plainData", "policyUid", b"policyUid"]) -> None: ...

global___PolicyNode = PolicyNode

@typing.final
class CollectionNode(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COLLECTIONUID_FIELD_NUMBER: builtins.int
    COLLECTIONTYPE_FIELD_NUMBER: builtins.int
    ENCRYPTEDDATA_FIELD_NUMBER: builtins.int
    CREATED_FIELD_NUMBER: builtins.int
    collectionUid: builtins.bytes
    collectionType: builtins.int
    """see CollectionLinkType"""
    encryptedData: builtins.bytes
    """collection data encrypted with the hash key"""
    created: builtins.int
    def __init__(
        self,
        *,
        collectionUid: builtins.bytes = ...,
        collectionType: builtins.int = ...,
        encryptedData: builtins.bytes = ...,
        created: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["collectionType", b"collectionType", "collectionUid", b"collectionUid", "created", b"created", "encryptedData", b"encryptedData"]) -> None: ...

global___CollectionNode = CollectionNode

@typing.final
class CollectionLink(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COLLECTIONUID_FIELD_NUMBER: builtins.int
    LINKUID_FIELD_NUMBER: builtins.int
    LINKTYPE_FIELD_NUMBER: builtins.int
    collectionUid: builtins.bytes
    linkUid: builtins.bytes
    linkType: global___CollectionLinkType.ValueType
    def __init__(
        self,
        *,
        collectionUid: builtins.bytes = ...,
        linkUid: builtins.bytes = ...,
        linkType: global___CollectionLinkType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["collectionUid", b"collectionUid", "linkType", b"linkType", "linkUid", b"linkUid"]) -> None: ...

global___CollectionLink = CollectionLink

@typing.final
class ApprovalStatusNode(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    APPROVALUID_FIELD_NUMBER: builtins.int
    APPROVALSTATUS_FIELD_NUMBER: builtins.int
    ENTERPRISEUSERID_FIELD_NUMBER: builtins.int
    MODIFIED_FIELD_NUMBER: builtins.int
    approvalUid: builtins.bytes
    approvalStatus: NotificationCenter_pb2.NotificationApprovalStatus.ValueType
    enterpriseUserId: builtins.int
    modified: builtins.int
    def __init__(
        self,
        *,
        approvalUid: builtins.bytes = ...,
        approvalStatus: NotificationCenter_pb2.NotificationApprovalStatus.ValueType = ...,
        enterpriseUserId: builtins.int = ...,
        modified: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["approvalStatus", b"approvalStatus", "approvalUid", b"approvalUid", "enterpriseUserId", b"enterpriseUserId", "modified", b"modified"]) -> None: ...

global___ApprovalStatusNode = ApprovalStatusNode

@typing.final
class ApprovalNode(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    APPROVALUID_FIELD_NUMBER: builtins.int
    APPROVALTYPE_FIELD_NUMBER: builtins.int
    AGENTUID_FIELD_NUMBER: builtins.int
    ACCOUNTINFO_FIELD_NUMBER: builtins.int
    APPLICATIONINFO_FIELD_NUMBER: builtins.int
    JUSTIFICATION_FIELD_NUMBER: builtins.int
    EXPIREIN_FIELD_NUMBER: builtins.int
    CREATED_FIELD_NUMBER: builtins.int
    approvalUid: builtins.bytes
    approvalType: builtins.int
    agentUid: builtins.bytes
    accountInfo: builtins.bytes
    applicationInfo: builtins.bytes
    justification: builtins.bytes
    expireIn: builtins.int
    created: builtins.int
    def __init__(
        self,
        *,
        approvalUid: builtins.bytes = ...,
        approvalType: builtins.int = ...,
        agentUid: builtins.bytes = ...,
        accountInfo: builtins.bytes = ...,
        applicationInfo: builtins.bytes = ...,
        justification: builtins.bytes = ...,
        expireIn: builtins.int = ...,
        created: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["accountInfo", b"accountInfo", "agentUid", b"agentUid", "applicationInfo", b"applicationInfo", "approvalType", b"approvalType", "approvalUid", b"approvalUid", "created", b"created", "expireIn", b"expireIn", "justification", b"justification"]) -> None: ...

global___ApprovalNode = ApprovalNode

@typing.final
class FullSyncToken(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STARTREVISION_FIELD_NUMBER: builtins.int
    ENTITY_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    startRevision: builtins.int
    entity: builtins.int
    @property
    def key(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        startRevision: builtins.int = ...,
        entity: builtins.int = ...,
        key: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["entity", b"entity", "key", b"key", "startRevision", b"startRevision"]) -> None: ...

global___FullSyncToken = FullSyncToken

@typing.final
class IncSyncToken(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LASTREVISION_FIELD_NUMBER: builtins.int
    lastRevision: builtins.int
    def __init__(
        self,
        *,
        lastRevision: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["lastRevision", b"lastRevision"]) -> None: ...

global___IncSyncToken = IncSyncToken

@typing.final
class PedmSyncToken(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FULLSYNC_FIELD_NUMBER: builtins.int
    INCSYNC_FIELD_NUMBER: builtins.int
    @property
    def fullSync(self) -> global___FullSyncToken: ...
    @property
    def incSync(self) -> global___IncSyncToken: ...
    def __init__(
        self,
        *,
        fullSync: global___FullSyncToken | None = ...,
        incSync: global___IncSyncToken | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fullSync", b"fullSync", "incSync", b"incSync", "token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fullSync", b"fullSync", "incSync", b"incSync", "token", b"token"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["token", b"token"]) -> typing.Literal["fullSync", "incSync"] | None: ...

global___PedmSyncToken = PedmSyncToken

@typing.final
class GetPedmDataRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTINUATIONTOKEN_FIELD_NUMBER: builtins.int
    continuationToken: builtins.bytes
    """empty value triggers full sync"""
    def __init__(
        self,
        *,
        continuationToken: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["continuationToken", b"continuationToken"]) -> None: ...

global___GetPedmDataRequest = GetPedmDataRequest

@typing.final
class GetPedmDataResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTINUATIONTOKEN_FIELD_NUMBER: builtins.int
    RESETCACHE_FIELD_NUMBER: builtins.int
    HASMORE_FIELD_NUMBER: builtins.int
    REMOVEDDEPLOYMENTS_FIELD_NUMBER: builtins.int
    REMOVEDAGENTS_FIELD_NUMBER: builtins.int
    REMOVEDPOLICIES_FIELD_NUMBER: builtins.int
    REMOVEDCOLLECTION_FIELD_NUMBER: builtins.int
    REMOVEDCOLLECTIONLINK_FIELD_NUMBER: builtins.int
    REMOVEDAPPROVALS_FIELD_NUMBER: builtins.int
    DEPLOYMENTS_FIELD_NUMBER: builtins.int
    AGENTS_FIELD_NUMBER: builtins.int
    POLICIES_FIELD_NUMBER: builtins.int
    COLLECTIONS_FIELD_NUMBER: builtins.int
    COLLECTIONLINK_FIELD_NUMBER: builtins.int
    APPROVALS_FIELD_NUMBER: builtins.int
    APPROVALSTATUS_FIELD_NUMBER: builtins.int
    continuationToken: builtins.bytes
    """sync token. send it with the next request"""
    resetCache: builtins.bool
    """if true the local cache needs to be cleared"""
    hasMore: builtins.bool
    """if true the client should immediately follow this up with another request"""
    @property
    def removedDeployments(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]:
        """UID list of removed deployments"""

    @property
    def removedAgents(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]:
        """UID list of removed agents"""

    @property
    def removedPolicies(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]:
        """UID list of removed policies"""

    @property
    def removedCollection(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]:
        """UID list of removed collections"""

    @property
    def removedCollectionLink(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CollectionLink]:
        """list of removed CollectionLink"""

    @property
    def removedApprovals(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]:
        """UID list of removed approvals"""

    @property
    def deployments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DeploymentNode]:
        """list of Deployment objects"""

    @property
    def agents(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AgentNode]:
        """list of Agent objects"""

    @property
    def policies(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PolicyNode]:
        """list of Policy objects"""

    @property
    def collections(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CollectionNode]:
        """list of Collection objects"""

    @property
    def collectionLink(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CollectionLink]:
        """list of CollectionLink objects"""

    @property
    def approvals(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ApprovalNode]:
        """list of approval objects"""

    @property
    def approvalStatus(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ApprovalStatusNode]:
        """list of approval status objects"""

    def __init__(
        self,
        *,
        continuationToken: builtins.bytes = ...,
        resetCache: builtins.bool = ...,
        hasMore: builtins.bool = ...,
        removedDeployments: collections.abc.Iterable[builtins.bytes] | None = ...,
        removedAgents: collections.abc.Iterable[builtins.bytes] | None = ...,
        removedPolicies: collections.abc.Iterable[builtins.bytes] | None = ...,
        removedCollection: collections.abc.Iterable[builtins.bytes] | None = ...,
        removedCollectionLink: collections.abc.Iterable[global___CollectionLink] | None = ...,
        removedApprovals: collections.abc.Iterable[builtins.bytes] | None = ...,
        deployments: collections.abc.Iterable[global___DeploymentNode] | None = ...,
        agents: collections.abc.Iterable[global___AgentNode] | None = ...,
        policies: collections.abc.Iterable[global___PolicyNode] | None = ...,
        collections: collections.abc.Iterable[global___CollectionNode] | None = ...,
        collectionLink: collections.abc.Iterable[global___CollectionLink] | None = ...,
        approvals: collections.abc.Iterable[global___ApprovalNode] | None = ...,
        approvalStatus: collections.abc.Iterable[global___ApprovalStatusNode] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["agents", b"agents", "approvalStatus", b"approvalStatus", "approvals", b"approvals", "collectionLink", b"collectionLink", "collections", b"collections", "continuationToken", b"continuationToken", "deployments", b"deployments", "hasMore", b"hasMore", "policies", b"policies", "removedAgents", b"removedAgents", "removedApprovals", b"removedApprovals", "removedCollection", b"removedCollection", "removedCollectionLink", b"removedCollectionLink", "removedDeployments", b"removedDeployments", "removedPolicies", b"removedPolicies", "resetCache", b"resetCache"]) -> None: ...

global___GetPedmDataResponse = GetPedmDataResponse

@typing.final
class AuditCollectionRequest(google.protobuf.message.Message):
    """PEDM Audit Collections"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTINUATIONTOKEN_FIELD_NUMBER: builtins.int
    VALUEUID_FIELD_NUMBER: builtins.int
    COLLECTIONNAME_FIELD_NUMBER: builtins.int
    continuationToken: builtins.bytes
    @property
    def valueUid(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    @property
    def collectionName(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        continuationToken: builtins.bytes = ...,
        valueUid: collections.abc.Iterable[builtins.bytes] | None = ...,
        collectionName: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["collectionName", b"collectionName", "continuationToken", b"continuationToken", "valueUid", b"valueUid"]) -> None: ...

global___AuditCollectionRequest = AuditCollectionRequest

@typing.final
class AuditCollectionValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COLLECTIONNAME_FIELD_NUMBER: builtins.int
    VALUEUID_FIELD_NUMBER: builtins.int
    ENCRYPTEDDATA_FIELD_NUMBER: builtins.int
    CREATED_FIELD_NUMBER: builtins.int
    collectionName: builtins.str
    valueUid: builtins.bytes
    encryptedData: builtins.bytes
    created: builtins.int
    def __init__(
        self,
        *,
        collectionName: builtins.str = ...,
        valueUid: builtins.bytes = ...,
        encryptedData: builtins.bytes = ...,
        created: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["collectionName", b"collectionName", "created", b"created", "encryptedData", b"encryptedData", "valueUid", b"valueUid"]) -> None: ...

global___AuditCollectionValue = AuditCollectionValue

@typing.final
class AuditCollectionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    HASMORE_FIELD_NUMBER: builtins.int
    CONTINUATIONTOKEN_FIELD_NUMBER: builtins.int
    hasMore: builtins.bool
    continuationToken: builtins.bytes
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AuditCollectionValue]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[global___AuditCollectionValue] | None = ...,
        hasMore: builtins.bool = ...,
        continuationToken: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["continuationToken", b"continuationToken", "hasMore", b"hasMore", "values", b"values"]) -> None: ...

global___AuditCollectionResponse = AuditCollectionResponse
