"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _MessageType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MessageTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MessageType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN: _MessageType.ValueType  # 0
    DNA: _MessageType.ValueType  # 1
    """to one specific messageSessionUid"""
    SSO: _MessageType.ValueType  # 2
    """not supported"""
    CHAT: _MessageType.ValueType  # 3
    """to all user's messageSessionUid except one specific messageSessionUid (origin)"""
    USER: _MessageType.ValueType  # 4
    """to all user's messageSessionUid except one specific messageSessionUid (origin)"""
    ENTERPRISE: _MessageType.ValueType  # 5
    """to all messageSessionUid for enterpriseId not equal current messageSessionUid"""
    KEEPER: _MessageType.ValueType  # 6
    """KA or Chat connects to or disconnects from PS"""
    SESSION: _MessageType.ValueType  # 7
    """to one specific messageSessionUid (somehow different from DNA)"""
    DEVICE: _MessageType.ValueType  # 8
    """to all devices"""
    TOTP: _MessageType.ValueType  # 9
    """to 2FA"""

class MessageType(_MessageType, metaclass=_MessageTypeEnumTypeWrapper): ...

UNKNOWN: MessageType.ValueType  # 0
DNA: MessageType.ValueType  # 1
"""to one specific messageSessionUid"""
SSO: MessageType.ValueType  # 2
"""not supported"""
CHAT: MessageType.ValueType  # 3
"""to all user's messageSessionUid except one specific messageSessionUid (origin)"""
USER: MessageType.ValueType  # 4
"""to all user's messageSessionUid except one specific messageSessionUid (origin)"""
ENTERPRISE: MessageType.ValueType  # 5
"""to all messageSessionUid for enterpriseId not equal current messageSessionUid"""
KEEPER: MessageType.ValueType  # 6
"""KA or Chat connects to or disconnects from PS"""
SESSION: MessageType.ValueType  # 7
"""to one specific messageSessionUid (somehow different from DNA)"""
DEVICE: MessageType.ValueType  # 8
"""to all devices"""
TOTP: MessageType.ValueType  # 9
"""to 2FA"""
global___MessageType = MessageType

@typing.final
class UserRegistrationRequest(google.protobuf.message.Message):
    """KA registers login/logout"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGESESSIONUID_FIELD_NUMBER: builtins.int
    USERID_FIELD_NUMBER: builtins.int
    ENTERPRISEID_FIELD_NUMBER: builtins.int
    messageSessionUid: builtins.bytes
    userId: builtins.int
    enterpriseId: builtins.int
    def __init__(
        self,
        *,
        messageSessionUid: builtins.bytes = ...,
        userId: builtins.int = ...,
        enterpriseId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["enterpriseId", b"enterpriseId", "messageSessionUid", b"messageSessionUid", "userId", b"userId"]) -> None: ...

global___UserRegistrationRequest = UserRegistrationRequest

@typing.final
class KAToPushServerRequest(google.protobuf.message.Message):
    """KA sends ws message"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGETYPE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    MESSAGESESSIONUID_FIELD_NUMBER: builtins.int
    ENCRYPTEDDEVICETOKEN_FIELD_NUMBER: builtins.int
    USERID_FIELD_NUMBER: builtins.int
    ENTERPRISEID_FIELD_NUMBER: builtins.int
    messageType: global___MessageType.ValueType
    message: builtins.str
    messageSessionUid: builtins.bytes
    @property
    def encryptedDeviceToken(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]:
        """aka platformDeviceToken"""

    @property
    def userId(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def enterpriseId(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        messageType: global___MessageType.ValueType = ...,
        message: builtins.str = ...,
        messageSessionUid: builtins.bytes = ...,
        encryptedDeviceToken: collections.abc.Iterable[builtins.bytes] | None = ...,
        userId: collections.abc.Iterable[builtins.int] | None = ...,
        enterpriseId: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["encryptedDeviceToken", b"encryptedDeviceToken", "enterpriseId", b"enterpriseId", "message", b"message", "messageSessionUid", b"messageSessionUid", "messageType", b"messageType", "userId", b"userId"]) -> None: ...

global___KAToPushServerRequest = KAToPushServerRequest

@typing.final
class WssConnectionRequest(google.protobuf.message.Message):
    """Client sends to push"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGESESSIONUID_FIELD_NUMBER: builtins.int
    ENCRYPTEDDEVICETOKEN_FIELD_NUMBER: builtins.int
    DEVICETIMESTAMP_FIELD_NUMBER: builtins.int
    messageSessionUid: builtins.bytes
    encryptedDeviceToken: builtins.bytes
    """aka platformDeviceToken"""
    deviceTimeStamp: builtins.int
    def __init__(
        self,
        *,
        messageSessionUid: builtins.bytes = ...,
        encryptedDeviceToken: builtins.bytes = ...,
        deviceTimeStamp: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["deviceTimeStamp", b"deviceTimeStamp", "encryptedDeviceToken", b"encryptedDeviceToken", "messageSessionUid", b"messageSessionUid"]) -> None: ...

global___WssConnectionRequest = WssConnectionRequest

@typing.final
class WssClientResponse(google.protobuf.message.Message):
    """PS sends to clients"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGETYPE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    messageType: global___MessageType.ValueType
    message: builtins.str
    def __init__(
        self,
        *,
        messageType: global___MessageType.ValueType = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "messageType", b"messageType"]) -> None: ...

global___WssClientResponse = WssClientResponse

@typing.final
class PushServerDeviceRegistrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENCRYPTEDDEVICETOKEN_FIELD_NUMBER: builtins.int
    PUSHTOKEN_FIELD_NUMBER: builtins.int
    MOBILEPUSHPLATFORM_FIELD_NUMBER: builtins.int
    TRANSMISSIONKEY_FIELD_NUMBER: builtins.int
    encryptedDeviceToken: builtins.bytes
    pushToken: builtins.str
    mobilePushPlatform: builtins.str
    transmissionKey: builtins.bytes
    def __init__(
        self,
        *,
        encryptedDeviceToken: builtins.bytes = ...,
        pushToken: builtins.str = ...,
        mobilePushPlatform: builtins.str = ...,
        transmissionKey: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["encryptedDeviceToken", b"encryptedDeviceToken", "mobilePushPlatform", b"mobilePushPlatform", "pushToken", b"pushToken", "transmissionKey", b"transmissionKey"]) -> None: ...

global___PushServerDeviceRegistrationRequest = PushServerDeviceRegistrationRequest

@typing.final
class SnsMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGETYPE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    messageType: global___MessageType.ValueType
    message: builtins.bytes
    def __init__(
        self,
        *,
        messageType: global___MessageType.ValueType = ...,
        message: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "messageType", b"messageType"]) -> None: ...

global___SnsMessage = SnsMessage
