"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import pam_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _RouterResponseCode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RouterResponseCodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RouterResponseCode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RRC_OK: _RouterResponseCode.ValueType  # 0
    RRC_GENERAL_ERROR: _RouterResponseCode.ValueType  # 1
    """Any other error"""
    RRC_NOT_ALLOWED: _RouterResponseCode.ValueType  # 2
    """Insufficient permissions"""
    RRC_BAD_REQUEST: _RouterResponseCode.ValueType  # 3
    """Malformed request"""
    RRC_TIMEOUT: _RouterResponseCode.ValueType  # 4
    RRC_BAD_STATE: _RouterResponseCode.ValueType  # 5
    """Some conditions are not met"""
    RRC_CONTROLLER_DOWN: _RouterResponseCode.ValueType  # 6
    """Controller is not listening"""
    RRC_WRONG_INSTANCE: _RouterResponseCode.ValueType  # 7
    """Controller is listening on a different instance"""
    RRC_NOT_ALLOWED_ENFORCEMENT_NOT_ENABLED: _RouterResponseCode.ValueType  # 8
    """access is restricted due to enforcement"""
    RRC_NOT_ALLOWED_PAM_CONFIG_FEATURES_NOT_ENABLED: _RouterResponseCode.ValueType  # 9
    """access is restricted due to pam configuration features"""

class RouterResponseCode(_RouterResponseCode, metaclass=_RouterResponseCodeEnumTypeWrapper): ...

RRC_OK: RouterResponseCode.ValueType  # 0
RRC_GENERAL_ERROR: RouterResponseCode.ValueType  # 1
"""Any other error"""
RRC_NOT_ALLOWED: RouterResponseCode.ValueType  # 2
"""Insufficient permissions"""
RRC_BAD_REQUEST: RouterResponseCode.ValueType  # 3
"""Malformed request"""
RRC_TIMEOUT: RouterResponseCode.ValueType  # 4
RRC_BAD_STATE: RouterResponseCode.ValueType  # 5
"""Some conditions are not met"""
RRC_CONTROLLER_DOWN: RouterResponseCode.ValueType  # 6
"""Controller is not listening"""
RRC_WRONG_INSTANCE: RouterResponseCode.ValueType  # 7
"""Controller is listening on a different instance"""
RRC_NOT_ALLOWED_ENFORCEMENT_NOT_ENABLED: RouterResponseCode.ValueType  # 8
"""access is restricted due to enforcement"""
RRC_NOT_ALLOWED_PAM_CONFIG_FEATURES_NOT_ENABLED: RouterResponseCode.ValueType  # 9
"""access is restricted due to pam configuration features"""
global___RouterResponseCode = RouterResponseCode

class _RouterRotationStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RouterRotationStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RouterRotationStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RRS_ONLINE: _RouterRotationStatus.ValueType  # 0
    RRS_NO_ROTATION: _RouterRotationStatus.ValueType  # 1
    RRS_NO_CONTROLLER: _RouterRotationStatus.ValueType  # 2
    RRS_CONTROLLER_DOWN: _RouterRotationStatus.ValueType  # 3

class RouterRotationStatus(_RouterRotationStatus, metaclass=_RouterRotationStatusEnumTypeWrapper): ...

RRS_ONLINE: RouterRotationStatus.ValueType  # 0
RRS_NO_ROTATION: RouterRotationStatus.ValueType  # 1
RRS_NO_CONTROLLER: RouterRotationStatus.ValueType  # 2
RRS_CONTROLLER_DOWN: RouterRotationStatus.ValueType  # 3
global___RouterRotationStatus = RouterRotationStatus

class _UserRecordAccessLevel:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _UserRecordAccessLevelEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UserRecordAccessLevel.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RRAL_NONE: _UserRecordAccessLevel.ValueType  # 0
    RRAL_READ: _UserRecordAccessLevel.ValueType  # 1
    RRAL_SHARE: _UserRecordAccessLevel.ValueType  # 2
    RRAL_EDIT: _UserRecordAccessLevel.ValueType  # 3
    RRAL_EDIT_AND_SHARE: _UserRecordAccessLevel.ValueType  # 4
    RRAL_OWNER: _UserRecordAccessLevel.ValueType  # 5

class UserRecordAccessLevel(_UserRecordAccessLevel, metaclass=_UserRecordAccessLevelEnumTypeWrapper): ...

RRAL_NONE: UserRecordAccessLevel.ValueType  # 0
RRAL_READ: UserRecordAccessLevel.ValueType  # 1
RRAL_SHARE: UserRecordAccessLevel.ValueType  # 2
RRAL_EDIT: UserRecordAccessLevel.ValueType  # 3
RRAL_EDIT_AND_SHARE: UserRecordAccessLevel.ValueType  # 4
RRAL_OWNER: UserRecordAccessLevel.ValueType  # 5
global___UserRecordAccessLevel = UserRecordAccessLevel

class _ServiceType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ServiceTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ServiceType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNSPECIFIED: _ServiceType.ValueType  # 0
    KA: _ServiceType.ValueType  # 1
    BI: _ServiceType.ValueType  # 2

class ServiceType(_ServiceType, metaclass=_ServiceTypeEnumTypeWrapper): ...

UNSPECIFIED: ServiceType.ValueType  # 0
KA: ServiceType.ValueType  # 1
BI: ServiceType.ValueType  # 2
global___ServiceType = ServiceType

@typing.final
class RouterResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESPONSECODE_FIELD_NUMBER: builtins.int
    ERRORMESSAGE_FIELD_NUMBER: builtins.int
    ENCRYPTEDPAYLOAD_FIELD_NUMBER: builtins.int
    responseCode: global___RouterResponseCode.ValueType
    errorMessage: builtins.str
    encryptedPayload: builtins.bytes
    def __init__(
        self,
        *,
        responseCode: global___RouterResponseCode.ValueType = ...,
        errorMessage: builtins.str = ...,
        encryptedPayload: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["encryptedPayload", b"encryptedPayload", "errorMessage", b"errorMessage", "responseCode", b"responseCode"]) -> None: ...

global___RouterResponse = RouterResponse

@typing.final
class RouterControllerMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGETYPE_FIELD_NUMBER: builtins.int
    MESSAGEUID_FIELD_NUMBER: builtins.int
    CONTROLLERUID_FIELD_NUMBER: builtins.int
    STREAMRESPONSE_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    messageType: pam_pb2.ControllerMessageType.ValueType
    messageUid: builtins.bytes
    controllerUid: builtins.bytes
    streamResponse: builtins.bool
    payload: builtins.bytes
    timeout: builtins.int
    def __init__(
        self,
        *,
        messageType: pam_pb2.ControllerMessageType.ValueType = ...,
        messageUid: builtins.bytes = ...,
        controllerUid: builtins.bytes = ...,
        streamResponse: builtins.bool = ...,
        payload: builtins.bytes = ...,
        timeout: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["controllerUid", b"controllerUid", "messageType", b"messageType", "messageUid", b"messageUid", "payload", b"payload", "streamResponse", b"streamResponse", "timeout", b"timeout"]) -> None: ...

global___RouterControllerMessage = RouterControllerMessage

@typing.final
class RouterUserAuth(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRANSMISSIONKEY_FIELD_NUMBER: builtins.int
    SESSIONTOKEN_FIELD_NUMBER: builtins.int
    USERID_FIELD_NUMBER: builtins.int
    ENTERPRISEUSERID_FIELD_NUMBER: builtins.int
    DEVICENAME_FIELD_NUMBER: builtins.int
    DEVICETOKEN_FIELD_NUMBER: builtins.int
    CLIENTVERSIONID_FIELD_NUMBER: builtins.int
    NEEDUSERNAME_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    MSPENTERPRISEID_FIELD_NUMBER: builtins.int
    ISPEDMADMIN_FIELD_NUMBER: builtins.int
    MCENTERPRISEID_FIELD_NUMBER: builtins.int
    transmissionKey: builtins.bytes
    sessionToken: builtins.bytes
    userId: builtins.int
    enterpriseUserId: builtins.int
    deviceName: builtins.str
    deviceToken: builtins.bytes
    clientVersionId: builtins.int
    needUsername: builtins.bool
    username: builtins.str
    mspEnterpriseId: builtins.int
    isPedmAdmin: builtins.bool
    mcEnterpriseId: builtins.int
    def __init__(
        self,
        *,
        transmissionKey: builtins.bytes = ...,
        sessionToken: builtins.bytes = ...,
        userId: builtins.int = ...,
        enterpriseUserId: builtins.int = ...,
        deviceName: builtins.str = ...,
        deviceToken: builtins.bytes = ...,
        clientVersionId: builtins.int = ...,
        needUsername: builtins.bool = ...,
        username: builtins.str = ...,
        mspEnterpriseId: builtins.int = ...,
        isPedmAdmin: builtins.bool = ...,
        mcEnterpriseId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["clientVersionId", b"clientVersionId", "deviceName", b"deviceName", "deviceToken", b"deviceToken", "enterpriseUserId", b"enterpriseUserId", "isPedmAdmin", b"isPedmAdmin", "mcEnterpriseId", b"mcEnterpriseId", "mspEnterpriseId", b"mspEnterpriseId", "needUsername", b"needUsername", "sessionToken", b"sessionToken", "transmissionKey", b"transmissionKey", "userId", b"userId", "username", b"username"]) -> None: ...

global___RouterUserAuth = RouterUserAuth

@typing.final
class RouterDeviceAuth(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLIENTID_FIELD_NUMBER: builtins.int
    CLIENTVERSION_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    ENTERPRISEID_FIELD_NUMBER: builtins.int
    NODEID_FIELD_NUMBER: builtins.int
    DEVICENAME_FIELD_NUMBER: builtins.int
    DEVICETOKEN_FIELD_NUMBER: builtins.int
    CONTROLLERNAME_FIELD_NUMBER: builtins.int
    CONTROLLERUID_FIELD_NUMBER: builtins.int
    OWNERUSER_FIELD_NUMBER: builtins.int
    CHALLENGE_FIELD_NUMBER: builtins.int
    OWNERID_FIELD_NUMBER: builtins.int
    clientId: builtins.str
    clientVersion: builtins.str
    signature: builtins.bytes
    enterpriseId: builtins.int
    nodeId: builtins.int
    deviceName: builtins.str
    deviceToken: builtins.bytes
    controllerName: builtins.str
    controllerUid: builtins.bytes
    ownerUser: builtins.str
    challenge: builtins.str
    ownerId: builtins.int
    def __init__(
        self,
        *,
        clientId: builtins.str = ...,
        clientVersion: builtins.str = ...,
        signature: builtins.bytes = ...,
        enterpriseId: builtins.int = ...,
        nodeId: builtins.int = ...,
        deviceName: builtins.str = ...,
        deviceToken: builtins.bytes = ...,
        controllerName: builtins.str = ...,
        controllerUid: builtins.bytes = ...,
        ownerUser: builtins.str = ...,
        challenge: builtins.str = ...,
        ownerId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["challenge", b"challenge", "clientId", b"clientId", "clientVersion", b"clientVersion", "controllerName", b"controllerName", "controllerUid", b"controllerUid", "deviceName", b"deviceName", "deviceToken", b"deviceToken", "enterpriseId", b"enterpriseId", "nodeId", b"nodeId", "ownerId", b"ownerId", "ownerUser", b"ownerUser", "signature", b"signature"]) -> None: ...

global___RouterDeviceAuth = RouterDeviceAuth

@typing.final
class RouterRecordRotation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORDUID_FIELD_NUMBER: builtins.int
    CONFIGURATIONUID_FIELD_NUMBER: builtins.int
    CONTROLLERUID_FIELD_NUMBER: builtins.int
    RESOURCEUID_FIELD_NUMBER: builtins.int
    NOSCHEDULE_FIELD_NUMBER: builtins.int
    recordUid: builtins.bytes
    configurationUid: builtins.bytes
    controllerUid: builtins.bytes
    resourceUid: builtins.bytes
    noSchedule: builtins.bool
    def __init__(
        self,
        *,
        recordUid: builtins.bytes = ...,
        configurationUid: builtins.bytes = ...,
        controllerUid: builtins.bytes = ...,
        resourceUid: builtins.bytes = ...,
        noSchedule: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["configurationUid", b"configurationUid", "controllerUid", b"controllerUid", "noSchedule", b"noSchedule", "recordUid", b"recordUid", "resourceUid", b"resourceUid"]) -> None: ...

global___RouterRecordRotation = RouterRecordRotation

@typing.final
class RouterRecordRotationsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTERPRISEID_FIELD_NUMBER: builtins.int
    RECORDS_FIELD_NUMBER: builtins.int
    enterpriseId: builtins.int
    @property
    def records(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        enterpriseId: builtins.int = ...,
        records: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["enterpriseId", b"enterpriseId", "records", b"records"]) -> None: ...

global___RouterRecordRotationsRequest = RouterRecordRotationsRequest

@typing.final
class RouterRecordRotationsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROTATIONS_FIELD_NUMBER: builtins.int
    HASMORE_FIELD_NUMBER: builtins.int
    hasMore: builtins.bool
    @property
    def rotations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RouterRecordRotation]: ...
    def __init__(
        self,
        *,
        rotations: collections.abc.Iterable[global___RouterRecordRotation] | None = ...,
        hasMore: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["hasMore", b"hasMore", "rotations", b"rotations"]) -> None: ...

global___RouterRecordRotationsResponse = RouterRecordRotationsResponse

@typing.final
class RouterRotationInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    CONFIGURATIONUID_FIELD_NUMBER: builtins.int
    RESOURCEUID_FIELD_NUMBER: builtins.int
    NODEID_FIELD_NUMBER: builtins.int
    CONTROLLERUID_FIELD_NUMBER: builtins.int
    CONTROLLERNAME_FIELD_NUMBER: builtins.int
    SCRIPTNAME_FIELD_NUMBER: builtins.int
    PWDCOMPLEXITY_FIELD_NUMBER: builtins.int
    DISABLED_FIELD_NUMBER: builtins.int
    status: global___RouterRotationStatus.ValueType
    configurationUid: builtins.bytes
    resourceUid: builtins.bytes
    nodeId: builtins.int
    controllerUid: builtins.bytes
    controllerName: builtins.str
    scriptName: builtins.str
    pwdComplexity: builtins.str
    disabled: builtins.bool
    def __init__(
        self,
        *,
        status: global___RouterRotationStatus.ValueType = ...,
        configurationUid: builtins.bytes = ...,
        resourceUid: builtins.bytes = ...,
        nodeId: builtins.int = ...,
        controllerUid: builtins.bytes = ...,
        controllerName: builtins.str = ...,
        scriptName: builtins.str = ...,
        pwdComplexity: builtins.str = ...,
        disabled: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["configurationUid", b"configurationUid", "controllerName", b"controllerName", "controllerUid", b"controllerUid", "disabled", b"disabled", "nodeId", b"nodeId", "pwdComplexity", b"pwdComplexity", "resourceUid", b"resourceUid", "scriptName", b"scriptName", "status", b"status"]) -> None: ...

global___RouterRotationInfo = RouterRotationInfo

@typing.final
class RouterRecordRotationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORDUID_FIELD_NUMBER: builtins.int
    REVISION_FIELD_NUMBER: builtins.int
    CONFIGURATIONUID_FIELD_NUMBER: builtins.int
    RESOURCEUID_FIELD_NUMBER: builtins.int
    SCHEDULE_FIELD_NUMBER: builtins.int
    ENTERPRISEUSERID_FIELD_NUMBER: builtins.int
    PWDCOMPLEXITY_FIELD_NUMBER: builtins.int
    DISABLED_FIELD_NUMBER: builtins.int
    REMOTEADDRESS_FIELD_NUMBER: builtins.int
    CLIENTVERSIONID_FIELD_NUMBER: builtins.int
    NOOP_FIELD_NUMBER: builtins.int
    recordUid: builtins.bytes
    revision: builtins.int
    configurationUid: builtins.bytes
    resourceUid: builtins.bytes
    schedule: builtins.str
    enterpriseUserId: builtins.int
    pwdComplexity: builtins.bytes
    disabled: builtins.bool
    remoteAddress: builtins.str
    clientVersionId: builtins.int
    noop: builtins.bool
    def __init__(
        self,
        *,
        recordUid: builtins.bytes = ...,
        revision: builtins.int = ...,
        configurationUid: builtins.bytes = ...,
        resourceUid: builtins.bytes = ...,
        schedule: builtins.str = ...,
        enterpriseUserId: builtins.int = ...,
        pwdComplexity: builtins.bytes = ...,
        disabled: builtins.bool = ...,
        remoteAddress: builtins.str = ...,
        clientVersionId: builtins.int = ...,
        noop: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["clientVersionId", b"clientVersionId", "configurationUid", b"configurationUid", "disabled", b"disabled", "enterpriseUserId", b"enterpriseUserId", "noop", b"noop", "pwdComplexity", b"pwdComplexity", "recordUid", b"recordUid", "remoteAddress", b"remoteAddress", "resourceUid", b"resourceUid", "revision", b"revision", "schedule", b"schedule"]) -> None: ...

global___RouterRecordRotationRequest = RouterRecordRotationRequest

@typing.final
class UserRecordAccessRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERID_FIELD_NUMBER: builtins.int
    RECORDUID_FIELD_NUMBER: builtins.int
    userId: builtins.int
    recordUid: builtins.bytes
    def __init__(
        self,
        *,
        userId: builtins.int = ...,
        recordUid: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["recordUid", b"recordUid", "userId", b"userId"]) -> None: ...

global___UserRecordAccessRequest = UserRecordAccessRequest

@typing.final
class UserRecordAccessResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORDUID_FIELD_NUMBER: builtins.int
    ACCESSLEVEL_FIELD_NUMBER: builtins.int
    recordUid: builtins.bytes
    accessLevel: global___UserRecordAccessLevel.ValueType
    def __init__(
        self,
        *,
        recordUid: builtins.bytes = ...,
        accessLevel: global___UserRecordAccessLevel.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["accessLevel", b"accessLevel", "recordUid", b"recordUid"]) -> None: ...

global___UserRecordAccessResponse = UserRecordAccessResponse

@typing.final
class RotationSchedule(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORD_UID_FIELD_NUMBER: builtins.int
    SCHEDULE_FIELD_NUMBER: builtins.int
    record_uid: builtins.bytes
    schedule: builtins.str
    def __init__(
        self,
        *,
        record_uid: builtins.bytes = ...,
        schedule: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["record_uid", b"record_uid", "schedule", b"schedule"]) -> None: ...

global___RotationSchedule = RotationSchedule

@typing.final
class ApiCallbackRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCEUID_FIELD_NUMBER: builtins.int
    SCHEDULES_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    SERVICETYPE_FIELD_NUMBER: builtins.int
    resourceUid: builtins.bytes
    url: builtins.str
    serviceType: global___ServiceType.ValueType
    @property
    def schedules(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ApiCallbackSchedule]: ...
    def __init__(
        self,
        *,
        resourceUid: builtins.bytes = ...,
        schedules: collections.abc.Iterable[global___ApiCallbackSchedule] | None = ...,
        url: builtins.str = ...,
        serviceType: global___ServiceType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["resourceUid", b"resourceUid", "schedules", b"schedules", "serviceType", b"serviceType", "url", b"url"]) -> None: ...

global___ApiCallbackRequest = ApiCallbackRequest

@typing.final
class ApiCallbackSchedule(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCHEDULE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    schedule: builtins.str
    data: builtins.bytes
    def __init__(
        self,
        *,
        schedule: builtins.str = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "schedule", b"schedule"]) -> None: ...

global___ApiCallbackSchedule = ApiCallbackSchedule

@typing.final
class RouterScheduledActions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCHEDULE_FIELD_NUMBER: builtins.int
    RESOURCEUIDS_FIELD_NUMBER: builtins.int
    schedule: builtins.str
    @property
    def resourceUids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        schedule: builtins.str = ...,
        resourceUids: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["resourceUids", b"resourceUids", "schedule", b"schedule"]) -> None: ...

global___RouterScheduledActions = RouterScheduledActions

@typing.final
class RouterRecordsRotationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROTATIONSCHEDULES_FIELD_NUMBER: builtins.int
    @property
    def rotationSchedules(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RouterScheduledActions]: ...
    def __init__(
        self,
        *,
        rotationSchedules: collections.abc.Iterable[global___RouterScheduledActions] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["rotationSchedules", b"rotationSchedules"]) -> None: ...

global___RouterRecordsRotationRequest = RouterRecordsRotationRequest

@typing.final
class ConnectionParameters(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONNECTIONUID_FIELD_NUMBER: builtins.int
    RECORDUID_FIELD_NUMBER: builtins.int
    USERID_FIELD_NUMBER: builtins.int
    CONTROLLERUID_FIELD_NUMBER: builtins.int
    CREDENTIALSRECORDUID_FIELD_NUMBER: builtins.int
    connectionUid: builtins.bytes
    recordUid: builtins.bytes
    userId: builtins.int
    controllerUid: builtins.bytes
    credentialsRecordUid: builtins.bytes
    def __init__(
        self,
        *,
        connectionUid: builtins.bytes = ...,
        recordUid: builtins.bytes = ...,
        userId: builtins.int = ...,
        controllerUid: builtins.bytes = ...,
        credentialsRecordUid: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["connectionUid", b"connectionUid", "controllerUid", b"controllerUid", "credentialsRecordUid", b"credentialsRecordUid", "recordUid", b"recordUid", "userId", b"userId"]) -> None: ...

global___ConnectionParameters = ConnectionParameters

@typing.final
class ValidateConnectionsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONNECTIONS_FIELD_NUMBER: builtins.int
    @property
    def connections(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ConnectionParameters]: ...
    def __init__(
        self,
        *,
        connections: collections.abc.Iterable[global___ConnectionParameters] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["connections", b"connections"]) -> None: ...

global___ValidateConnectionsRequest = ValidateConnectionsRequest

@typing.final
class ConnectionValidationFailure(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONNECTIONUID_FIELD_NUMBER: builtins.int
    ERRORMESSAGE_FIELD_NUMBER: builtins.int
    connectionUid: builtins.bytes
    errorMessage: builtins.str
    def __init__(
        self,
        *,
        connectionUid: builtins.bytes = ...,
        errorMessage: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["connectionUid", b"connectionUid", "errorMessage", b"errorMessage"]) -> None: ...

global___ConnectionValidationFailure = ConnectionValidationFailure

@typing.final
class ValidateConnectionsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FAILEDCONNECTIONS_FIELD_NUMBER: builtins.int
    @property
    def failedConnections(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ConnectionValidationFailure]: ...
    def __init__(
        self,
        *,
        failedConnections: collections.abc.Iterable[global___ConnectionValidationFailure] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["failedConnections", b"failedConnections"]) -> None: ...

global___ValidateConnectionsResponse = ValidateConnectionsResponse

@typing.final
class GetEnforcementRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTERPRISEUSERID_FIELD_NUMBER: builtins.int
    enterpriseUserId: builtins.int
    def __init__(
        self,
        *,
        enterpriseUserId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["enterpriseUserId", b"enterpriseUserId"]) -> None: ...

global___GetEnforcementRequest = GetEnforcementRequest

@typing.final
class EnforcementType(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENFORCEMENTTYPEID_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    enforcementTypeId: builtins.int
    value: builtins.str
    def __init__(
        self,
        *,
        enforcementTypeId: builtins.int = ...,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["enforcementTypeId", b"enforcementTypeId", "value", b"value"]) -> None: ...

global___EnforcementType = EnforcementType

@typing.final
class GetEnforcementResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENFORCEMENTTYPES_FIELD_NUMBER: builtins.int
    ADDONIDS_FIELD_NUMBER: builtins.int
    ISINTRIAL_FIELD_NUMBER: builtins.int
    isInTrial: builtins.bool
    @property
    def enforcementTypes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EnforcementType]: ...
    @property
    def addOnIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        enforcementTypes: collections.abc.Iterable[global___EnforcementType] | None = ...,
        addOnIds: collections.abc.Iterable[builtins.int] | None = ...,
        isInTrial: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["addOnIds", b"addOnIds", "enforcementTypes", b"enforcementTypes", "isInTrial", b"isInTrial"]) -> None: ...

global___GetEnforcementResponse = GetEnforcementResponse

@typing.final
class PEDMTOTPValidateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    ENTERPRISEID_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    username: builtins.str
    enterpriseId: builtins.int
    code: builtins.int
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        enterpriseId: builtins.int = ...,
        code: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["code", b"code", "enterpriseId", b"enterpriseId", "username", b"username"]) -> None: ...

global___PEDMTOTPValidateRequest = PEDMTOTPValidateRequest
