[metadata]
name = keepersdk
version = attr: keepersdk.__init__.__version__
description = Keeper SDK for Python 3
long_description = file: README.md
long_description_content_type = text/markdown
author = Keeper Security Inc.
author_email = commander@keepersecurity.com
url = https://github.com/Keeper-Security/keeper-sdk-python
license = MIT
classifiers =
    Environment :: Console
    Development Status :: 4 - Beta
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Natural Language :: English
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Programming Language :: Python :: 3.14
    Topic :: Security
keywords = security, password

[options]
python_requires = >=3.10
package_dir =
    = src
include_package_data = True
install_requires =
    attrs>=25.4.0
    requests>=2.32.5
    cryptography>=45.0.7
    protobuf>=5.29.5
    websockets>=14.2
    fido2>=2.1.0
    email-validator>=2.3.0
    pydantic>=2.12.5
    google-api-core>=2.25.2
    tzlocal>=5.2.0

[options.package_data]
keepersdk =
  resources/*