from ...storage import dag

PEDM_GRAPH_ID = 20

AGENT_STREAM_REF_TYPE = dag.RefType.PAM_NETWORK
AGENT_REF_TYPE = dag.RefType.GENERAL
POLICY_REF_TYPE = dag.RefType.GENERAL
UNIT_REF_TYPE = dag.RefType.GENERAL
ENTERPRISE_REF_TYPE = dag.RefType.PAM_NETWORK

UNIT_DB_TYPE = 10
POLICY_DB_TYPE = 11

AGENT_UNIT_DB_TYPE = 13
POLICY_KEY_DB_TYPE = 15
UNIT_PARENT_DB_TYPE = 16

ENTERPRISE_KEY = '1D7s5W1MykizFUOMNWn8guf5PT7CTrU0f1syF5QUrAQ'
AGENT_KEY = '4S5ljQRMlXaPAGQGXJrhFKK527WqpICzxTZwcs1bYUk'