from typing import Optional, TypeVar, Iterable, Generic, Tuple, Union

T = TypeVar('T')

class IRecordStorage(Generic[T]):
    def load(self) -> Optional[T]: ...
    def store(self, record: T) -> None: ...
    def delete(self) -> None: ...

K = TypeVar('K', int, str, bytes)
class IUid(Generic[K]):
    def uid(self) -> K: ...

class IEntityStorage(Generic[T, K]):
    def get_entity(self, uid: K) -> Optional[T]:  ...
    def get_all(self) -> Iterable[T]: ...
    def put_entities(self, entities: Iterable[T]) -> None:  ...
    def delete_uids(self, uids: Iterable[K]) -> None: ...


KS = TypeVar('KS', int, str, bytes)
KO = TypeVar('KO', int, str, bytes)

class IUidLink(Generic[KS, KO]):
    def subject_uid(self) -> KS: ...
    def object_uid(self) -> KO: ...


class ILinkStorage(Generic[T, KS, KO]):
    def put_links(self, links: Iterable[T]) -> None: ...
    def delete_links(self, links: Iterable[Union[Tuple[KS, KO], IUidLink[KS, KO]]]) -> None: ...
    def delete_links_for_subjects(self, subject_uids: Iterable[KS]) -> None: ...
    def delete_links_for_objects(self, object_uids: Iterable[KO]) -> None: ...
    def get_links_for_subject(self, subject_uid: KS) -> Iterable[T]: ...
    def get_links_for_object(self, object_uid: KO) -> Iterable[T]: ...
    def get_all_links(self) -> Iterable[T]: ...

class UidLink(IUidLink[KS, KO]):
    def __init__(self, subject_uid: KS, object_uid: KO): ...
