from typing import Optional, TypeVar, Iterator, Union, Generic

def adjust_servername(server: str) -> str: ...
def adjust_username(username: str) -> str: ...

class IEntityId:
    def get_id(self) -> str: ...

TID = TypeVar('TID', bound=IEntityId)

class IConfigurationCollection(Generic[TID]):
    def get(self, entity_id: str) -> Optional[TID]: ...
    def put(self, entity: TID) -> None: ...
    def delete(self, entity_id: str) -> None: ...
    def list(self) -> Iterator[TID]: ...

class IDeviceServerConfiguration(IEntityId):
    def get_server(self) -> str: ...
    def get_clone_code(self) -> Optional[str]: ...

class IDeviceConfiguration(IEntityId):
    def get_device_token(self) -> str: ...
    def get_public_key(self) -> str: ...
    def get_private_key(self) -> str: ...
    def get_server_info(self) -> IConfigurationCollection[IDeviceServerConfiguration]: ...

class IUserDeviceConfiguration(IEntityId):
    def get_device_token(self) -> str: ...

class IUserConfiguration(IEntityId):
    def get_username(self) -> str: ...
    def get_password(self) -> Optional[str]: ...
    def get_server(self) -> str: ...
    def get_last_device(self) -> Optional[IUserDeviceConfiguration]: ...

class IServerConfiguration(IEntityId):
    def get_server(self) -> str: ...
    def get_server_key_id(self) -> int: ...

class IKeeperConfiguration:
    def get_last_login(self) -> str: ...
    def get_last_server(self) -> str: ...
    def set_last_login(self, value: str) -> None: ...
    def set_last_server(self, value: str) -> None: ...

    def users(self) -> IConfigurationCollection[IUserConfiguration]: ...
    def servers(self) -> IConfigurationCollection[IServerConfiguration]: ...
    def devices(self) -> IConfigurationCollection[IDeviceConfiguration]: ...
    def assign(self, other: IKeeperConfiguration) -> None: ...

class IConfigurationStorage:
    def get(self) -> IKeeperConfiguration: ...
    def put(self, configuration: IKeeperConfiguration) -> None: ...

class UserConfiguration(IUserConfiguration):
    def __init__(self, user: Union[str, IUserConfiguration]) -> None: ...
    password: Optional[str]
    server: str
    last_device: Optional[IUserDeviceConfiguration]

class ServerConfiguration(IServerConfiguration):
    def __init__(self, server: Union[str, IServerConfiguration]) -> None: ...
    server_key_id: int

class DeviceConfiguration(IDeviceConfiguration):
    def __init__(self, device: Union[str, IDeviceConfiguration]) -> None: ...
    public_key: str
    private_key: str

class UserDeviceConfiguration(IUserDeviceConfiguration):
    def __init__(self, user_device: Union[str, IUserDeviceConfiguration]) -> None: ...

class DeviceServerConfiguration(IDeviceServerConfiguration):
    def __init__(self, device_server: Union[str, IDeviceServerConfiguration]) -> None: ...
    clone_code: str

class KeeperConfiguration(IKeeperConfiguration):
    def __init__(self, other: Optional[IKeeperConfiguration] = None) -> None: ...

class InMemoryConfigurationStorage(IConfigurationStorage):
    def __init__(self, configuration: KeeperConfiguration) -> None: ...

class IJsonLoader:
    def load_json(self) -> bytes: ...
    def store_json(self, data: bytes) -> None: ...

class JsonFileLoader(IJsonLoader):
    def __init__(self, file_name: Optional[str] = None) -> None: ...

class JsonConfigurationStorage(IConfigurationStorage):
    def __init__(self, loader: Optional[IJsonLoader] = None, file_name: Optional[str] = None) -> None: ...
    loader: IJsonLoader
