from typing import TypeVar, Generic, Dict, Any, Callable, Optional

M = TypeVar('M')

class FanOut(Generic[M]):
    def register_callback(self, callback: Callable[[M], Optional[bool]]) -> None: ...
    def remove_callback(self, callback: Callable[[M], Optional[bool]]) -> None: ...
    def remove_all(self) -> None: ...
    def push(self, message: M) -> None: ...
    @property
    def is_completed(self) -> bool: ...
    def shutdown(self) -> None: ...

class KeeperPushNotifications(FanOut[Dict[str, Any]]):
    def __init__(self, transmission_key: bytes) -> None: ...
    def send_to_push_channel(self, data: bytes, encrypted: bool) -> None: ...
    def connect_to_push_channel(self, endpoint_uri: str) -> None: ...
